# Shared configuration - locale settings for host and VMs
# Generated by setup.sh
{
  timezone = "Europe/Stockholm";
  locale = "en_US.UTF-8";
  consoleKeymap = "sv-latin1";
  xkbLayout = "se";
  xkbVariant = "";
}
