# Auto-Include Module - Automatically import packages from profile directories
#
# This module looks for packages at profiles/<vmType>/packages/ and imports them
# into environment.systemPackages. Each package is a .nix file that returns a
# function taking { pkgs } and returning a derivation.
#
# Package file format (profiles/<vmType>/packages/foo.nix):
#   { pkgs }:
#   pkgs.rustPlatform.buildRustPackage {
#     pname = "foo";
#     ...
#   }
#
# The default.nix aggregator is auto-generated by vm-sync pull.
#
{ config, lib, pkgs, ... }:

let
  vmType = config.hydrix.vmType;

  # Path to packages directory relative to this module
  packagesPath = ../../profiles/${vmType}/packages;

  # Check if the packages directory exists and has a default.nix
  hasPackages = vmType != "" && builtins.pathExists (packagesPath + "/default.nix");

  # Import the packages list from default.nix
  # default.nix should return a function { pkgs }: [ ... ]
  packagesList = if hasPackages
    then import packagesPath { inherit pkgs; }
    else [];

in {
  config = lib.mkIf hasPackages {
    environment.systemPackages = packagesList;
  };
}
