# Dunst Notification Daemon Configuration
#
# Split into two config files, like alacritty.toml/colors-runtime.toml:
# - dunstrc-layout: everything except colors (offset, sizing, timeouts, font).
#   Written only by home.activation, unconditionally overwritten on every
#   rebuild - never touched by a colorscheme change. Safe to hand-edit for
#   testing between rebuilds.
# - dunstrc-colors: background/foreground/frame_color per urgency level only.
#   Written by generate-dunstrc-colors, unconditionally overwritten on every
#   rebuild AND on every walrgb/randomwalrgb colorscheme change (same trigger
#   as write-alacritty-colors), so it must never carry hand edits.
# dunst merges both via multiple -config flags (later files override earlier
# keys within the same section), so the daemon just runs against combined
# state.
#
# Notifications appear top-right. X offset is gaps + ui.dunstOffset from the screen
# edge, mirroring a tiled window's gaps_out on the sides. Y offset is ui.dunstOffset
# alone: Hyprland's exclusive-zone reservation for the bar already pushes dunst below
# it the same way gaps_out top=0 already pushes tiled windows below it, so no gaps or
# barHeight term belongs on this axis. Both axes end up leaving the same ui.dunstOffset
# clearance from a tiled window's edge.
#
# This module:
# - Disables home-manager's dunst service (we manage it ourselves)
# - Provides layout + colors generation scripts
# - Creates a systemd user service that runs dunst against both config files
{
  config,
  lib,
  pkgs,
  ...
}: let
  username = config.hydrix.username;
  cfg = config.hydrix.graphical;

  fontName = cfg.font.family;
  fontSize = cfg.font.size;

  generateDunstLayout = pkgs.writeShellScript "generate-dunstrc-layout" ''
    #!/usr/bin/env bash
    # Generate dunstrc-layout: sizing/timeouts/font from Nix config, no colors.

    DUNST_DIR="$HOME/.config/dunst"
    DUNSTRC="$DUNST_DIR/dunstrc-layout"

    ${pkgs.coreutils}/bin/mkdir -p "$DUNST_DIR"

    GAPS=${toString cfg.ui.gaps}
    BAR_HEIGHT=${toString cfg.ui.barHeight}
    BORDER=${toString cfg.ui.border}
    CORNER_RADIUS=${toString cfg.ui.cornerRadius}
    FONT_NAME="${fontName}"
    FONT_SIZE=${toString fontSize}
    DUNST_WIDTH=${toString cfg.ui.dunstWidth}
    DUNST_OFFSET=${toString cfg.ui.dunstOffset}

    # Padding scaled from bar height
    PADDING=$((BAR_HEIGHT / 4))
    [ "$PADDING" -lt 4 ] && PADDING=4
    [ "$PADDING" -gt 8 ] && PADDING=8
    H_PADDING=$((PADDING + 4))

    # Pill radius: matches waybar island pills (cornerRadius * pillRadiusScale)
    PILL_RADIUS=$((CORNER_RADIUS * ${toString (builtins.floor cfg.ui.pillRadiusScale)}))

    # Offset (see module header): X = gaps + dunstOffset, Y = dunstOffset
    OFFSET_X=$((GAPS + DUNST_OFFSET))
    OFFSET_Y=$DUNST_OFFSET

    ${pkgs.coreutils}/bin/cat > "$DUNSTRC" << DUNSTRC_EOF
    # Generated by Hydrix on rebuild - edit freely, restored on next rebuild

    [global]
    font = $FONT_NAME $FONT_SIZE

    monitor = ${
      if cfg.ui.dunstEnablePopup
      then "0"
      else "-1"
    }
    follow = mouse

    width = $DUNST_WIDTH
    height = 300
    origin = top-right
    offset = ''${OFFSET_X}x''${OFFSET_Y}
    scale = 0

    progress_bar = true
    progress_bar_height = 10
    progress_bar_frame_width = 1
    progress_bar_min_width = 150
    progress_bar_max_width = 300

    notification_limit = 5
    indicate_hidden = true
    transparency = 0
    separator_height = 0
    padding = $PADDING
    horizontal_padding = $H_PADDING
    text_icon_padding = 0
    frame_width = $BORDER
    gap_size = 0
    separator_color = frame
    sort = true

    line_height = 0
    markup = full
    format = "<b>%s</b>\n%b"
    alignment = left
    vertical_alignment = center
    show_age_threshold = 60
    ellipsize = middle
    word_wrap = yes
    ignore_newline = false
    stack_duplicates = true
    hide_duplicate_count = false
    show_indicators = true

    enable_recursive_icon_lookup = true
    icon_position = left
    min_icon_size = 32
    max_icon_size = 64

    sticky_history = true
    history_length = 20

    browser = ${cfg.ui.dunstBrowser}
    always_run_script = true
    title = Dunst
    class = Dunst
    corner_radius = $PILL_RADIUS
    ignore_dbusclose = false
    sound = ${
      if cfg.ui.dunstSound != null && cfg.ui.dunstSound != ""
      then "true"
      else "false"
    }
    sound_command = ${
      if cfg.ui.dunstSound != null && cfg.ui.dunstSound != ""
      then "canberra-gtk-play -f ${cfg.ui.dunstSound}"
      else ""
    }

    mouse_left_click = close_current
    mouse_middle_click = do_action, close_current
    mouse_right_click = close_all

    [urgency_low]
    timeout = ${toString cfg.ui.dunstUrgencyTimeout.low}

    [urgency_normal]
    timeout = ${toString cfg.ui.dunstUrgencyTimeout.normal}

    [urgency_critical]
    timeout = ${toString cfg.ui.dunstUrgencyTimeout.critical}
    DUNSTRC_EOF
  '';

  generateDunstColors = pkgs.writeShellScript "generate-dunstrc-colors" ''
    #!/usr/bin/env bash
    # Generate dunstrc-colors from the wal colors cache. Called on rebuild and
    # on every colorscheme change (walrgb, randomwalrgb) - never hand-edit this.

    DUNST_DIR="$HOME/.config/dunst"
    DUNSTRC="$DUNST_DIR/dunstrc-colors"

    ${pkgs.coreutils}/bin/mkdir -p "$DUNST_DIR"

    OVERLAY_ALPHA="D9"
    PREFIX_DEFAULT="#e0af68"
    FG_DEFAULT="#c0caf5"

    WAL_COLORS="$HOME/.cache/wal/colors.json"
    if [ -f "$WAL_COLORS" ]; then
      BG_RAW=$(${pkgs.jq}/bin/jq -r '.special.background // .colors.color0' "$WAL_COLORS")
      FG=$(${pkgs.jq}/bin/jq -r '.special.foreground // .colors.color7' "$WAL_COLORS")
      PREFIX=$(${pkgs.jq}/bin/jq -r '.colors.color3' "$WAL_COLORS")
      FRAME=$(${pkgs.jq}/bin/jq -r '.colors.color5' "$WAL_COLORS")
      FRAME_LOW=$(${pkgs.jq}/bin/jq -r '.colors.color2' "$WAL_COLORS")
      FRAME_CRIT=$(${pkgs.jq}/bin/jq -r '.colors.color1' "$WAL_COLORS")
    else
      BG_RAW="#101116"
      FG="$FG_DEFAULT"
      PREFIX="$PREFIX_DEFAULT"
      FRAME="#bb9af7"
      FRAME_LOW="#98971a"
      FRAME_CRIT="#cc241d"
    fi
    BG="''${BG_RAW}''${OVERLAY_ALPHA}"

    ${pkgs.coreutils}/bin/cat > "$DUNSTRC" << DUNSTRC_EOF
    # Generated by Hydrix from wal colors - do not edit, overwritten on every colorscheme change

    [global]
    format = "<b><span foreground='$PREFIX'>%s</span></b>\n<span foreground='$FG'>%b</span>"

    [urgency_low]
    background = "$BG"
    foreground = "$FG"
    frame_color = "$FRAME_LOW"

    [urgency_normal]
    background = "$BG"
    foreground = "$FG"
    frame_color = "$FRAME"

    [urgency_critical]
    background = "$BG"
    foreground = "$FG"
    frame_color = "$FRAME_CRIT"
    DUNSTRC_EOF
  '';
in {
  config = lib.mkIf cfg.enable {
    environment.systemPackages = [
      pkgs.dunst
      pkgs.libnotify
      (pkgs.runCommand "generate-dunstrc-layout" {} ''
        mkdir -p $out/bin
        cp ${generateDunstLayout} $out/bin/generate-dunstrc-layout
        chmod +x $out/bin/generate-dunstrc-layout
      '')
      (pkgs.runCommand "generate-dunstrc-colors" {} ''
        mkdir -p $out/bin
        cp ${generateDunstColors} $out/bin/generate-dunstrc-colors
        chmod +x $out/bin/generate-dunstrc-colors
      '')
    ];

    home-manager.users.${username} = {lib, ...}: {
      services.dunst.enable = false;

      # Layout: rebuild-only, unconditional overwrite, hand-editable in between.
      # Colors: also written here so a fresh rebuild has content immediately;
      # walrgb/randomwalrgb keep it fresh afterward via generate-dunstrc-colors.
      home.activation.writeDunstrc = lib.hm.dag.entryAfter ["writeBoundary"] ''
        ${generateDunstLayout}
        ${generateDunstColors}

        # Restart so placement/sizing changes actually apply. try-restart is a
        # no-op if dunst isn't running yet (first boot, headless rebuild).
        ${pkgs.systemd}/bin/systemctl --user try-restart dunst.service 2>/dev/null || true
      '';

      systemd.user.services.dunst = {
        Unit = {
          Description = "Dunst notification daemon (Hydrix)";
          Documentation = "man:dunst(1)";
          PartOf = ["graphical-session.target"];
          After = ["graphical-session-pre.target" "home.activation"];
        };
        Service = {
          Type = "dbus";
          BusName = "org.freedesktop.Notifications";
          ExecStart = "${pkgs.dunst}/bin/dunst -config %h/.config/dunst/dunstrc-layout -config %h/.config/dunst/dunstrc-colors";
          Restart = "on-failure";
          RestartSec = 1;
          ExecReload = "${pkgs.coreutils}/bin/kill -HUP $MAINPID";
        };
        Install = {
          WantedBy = ["graphical-session.target"];
        };
      };
    };
  };
}
