# GTK Theme Configuration
#
# Home Manager module for GTK theming.
# This affects GTK applications including:
# - Firefox file picker dialog
# - virt-manager
# - PCManFM and other file managers
# - Any GTK-based application
#
# Colors come from pywal at runtime via gtk-wal.css, generated by
# refresh-colors / walrgb. Stylix GTK theming is disabled to prevent
# its build-time colors from overriding the runtime wal colors.

{ config, lib, pkgs, ... }:

let
  username = config.hydrix.username;
  jq = "${pkgs.jq}/bin/jq";

  generateGtkColorsScript = pkgs.writeShellScriptBin "generate-gtk-colors" ''
    #!/usr/bin/env bash
    # Generate ~/.config/gtk-{3,4}.0/gtk-wal.css from pywal colors.
    # Called by refresh-colors after walrgb/randomwalrgb.

    WAL_COLORS="$HOME/.cache/wal/colors.json"

    if [ ! -f "$WAL_COLORS" ]; then
      echo "generate-gtk-colors: no wal cache, skipping" >&2
      exit 0
    fi

    mkdir -p "$HOME/.config/gtk-3.0" "$HOME/.config/gtk-4.0"

    GTK_WAL_CSS=$(${jq} -r '
      .special as $s | .colors as $c |
      [
        "@define-color accent_color \($c.color4);",
        "@define-color accent_bg_color \($c.color4);",
        "@define-color accent_fg_color \($s.background);",
        "@define-color destructive_color \($c.color1);",
        "@define-color destructive_bg_color \($c.color1);",
        "@define-color destructive_fg_color \($s.background);",
        "@define-color success_color \($c.color2);",
        "@define-color success_bg_color \($c.color2);",
        "@define-color success_fg_color \($s.background);",
        "@define-color warning_color \($c.color3);",
        "@define-color warning_bg_color \($c.color3);",
        "@define-color warning_fg_color \($s.background);",
        "@define-color error_color \($c.color1);",
        "@define-color error_bg_color \($c.color1);",
        "@define-color error_fg_color \($s.background);",
        "@define-color window_bg_color \($c.color0);",
        "@define-color window_fg_color \($s.foreground);",
        "@define-color view_bg_color \($c.color0);",
        "@define-color view_fg_color \($s.foreground);",
        "@define-color headerbar_bg_color \($c.color0);",
        "@define-color headerbar_fg_color \($s.foreground);",
        "@define-color headerbar_border_color \($c.color0);",
        "@define-color headerbar_backdrop_color \($c.color0);",
        "@define-color headerbar_shade_color rgba(0,0,0,0.07);",
        "@define-color headerbar_darker_shade_color rgba(0,0,0,0.07);",
        "@define-color sidebar_bg_color \($c.color0);",
        "@define-color sidebar_fg_color \($s.foreground);",
        "@define-color sidebar_backdrop_color \($c.color0);",
        "@define-color sidebar_shade_color rgba(0,0,0,0.07);",
        "@define-color secondary_sidebar_bg_color \($c.color0);",
        "@define-color secondary_sidebar_fg_color \($s.foreground);",
        "@define-color secondary_sidebar_backdrop_color \($c.color0);",
        "@define-color secondary_sidebar_shade_color rgba(0,0,0,0.07);",
        "@define-color card_bg_color \($c.color0);",
        "@define-color card_fg_color \($s.foreground);",
        "@define-color card_shade_color rgba(0,0,0,0.07);",
        "@define-color dialog_bg_color \($c.color0);",
        "@define-color dialog_fg_color \($s.foreground);",
        "@define-color popover_bg_color \($c.color0);",
        "@define-color popover_fg_color \($s.foreground);",
        "@define-color popover_shade_color rgba(0,0,0,0.07);",
        "@define-color shade_color rgba(0,0,0,0.07);",
        "@define-color scrollbar_outline_color \($c.color0);"
      ] + [
        ["blue","green","yellow","orange","red","purple","brown","light","dark"][] |
        . as $name |
        (if   $name == "blue"   then $c.color4
         elif $name == "green"  then $c.color2
         elif $name == "yellow" then $c.color3
         elif $name == "orange" then $c.color3
         elif $name == "red"    then $c.color1
         elif $name == "purple" then $c.color5
         elif $name == "brown"  then $c.color1
         elif $name == "light"  then $s.foreground
         else $c.color8
         end) as $hex |
        range(1;6) |
        "@define-color \($name)_\(.) \($hex);"
      ] | join("\n")
    ' "$WAL_COLORS")

    printf '%s\n' "$GTK_WAL_CSS" > "$HOME/.config/gtk-3.0/gtk-wal.css"
    cp "$HOME/.config/gtk-3.0/gtk-wal.css" "$HOME/.config/gtk-4.0/gtk-wal.css"

    # Force running GTK3 apps (Firefox, file pickers, etc.) to reload CSS.
    # Briefly switching the theme triggers GTK to re-read all CSS including @import.
    if command -v gsettings >/dev/null 2>&1; then
      CURRENT_THEME=$(gsettings get org.gnome.desktop.interface gtk-theme 2>/dev/null | tr -d "'")
      gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita' 2>/dev/null || true
      gsettings set org.gnome.desktop.interface gtk-theme "''${CURRENT_THEME:-adw-gtk3-dark}" 2>/dev/null || true
    fi
  '';

in {
  config = lib.mkIf config.hydrix.graphical.enable {
    environment.systemPackages = [ generateGtkColorsScript ];

    home-manager.users.${username} = { pkgs, config, ... }: {
      # Stylix injects build-time colors into gtk.css which override runtime wal
      # colors. Disable it so wal owns GTK colors entirely via gtk-wal.css.
      stylix.targets.gtk.enable = lib.mkForce false;

      # GTK 2/3/4 Configuration
      gtk = {
        enable = lib.mkDefault true;

        # Use adw-gtk3 as the base theme (Stylix would have set this)
        theme = {
          package = lib.mkDefault pkgs.adw-gtk3;
          name = lib.mkDefault "adw-gtk3-dark";
        };

        gtk2.extraConfig = ''
          gtk-application-prefer-dark-theme = 1
        '';

        gtk3 = {
          extraConfig = {
            gtk-application-prefer-dark-theme = true;
            gtk-decoration-layout = "menu:close";
          };
          # Import wal colors at runtime (generated by refresh-colors / walrgb)
          extraCss = ''@import url("gtk-wal.css");'';
        };

        gtk4.extraConfig = {
          gtk-application-prefer-dark-theme = true;
          gtk-decoration-layout = "menu:close";
        };

        # Icon theme
        iconTheme = {
          package = lib.mkDefault pkgs.papirus-icon-theme;
          name = lib.mkDefault "Papirus-Dark";
        };

        # Cursor theme
        cursorTheme = {
          package = lib.mkDefault pkgs.vanilla-dmz;
          name = lib.mkDefault "Vanilla-DMZ";
          size = lib.mkDefault 24;
        };
      };

      # Pointer cursor — applies to all environments (X11, Wayland/Hyprland, Sway)
      # Without this, Hyprland shows its default cursor on installs without i3.
      # mkDefault so xsession.nix's definition wins when i3 is also enabled.
      home.pointerCursor = lib.mkDefault {
        name = "Vanilla-DMZ";
        package = pkgs.vanilla-dmz;
        size = 24;
        gtk.enable = true;
      };

      # GTK4 wal colors import — home-manager's gtk module doesn't expose
      # gtk4.extraCss, so manage the file directly.
      xdg.configFile."gtk-4.0/gtk.css".text = ''@import url("gtk-wal.css");'';

      # Qt configuration - let Stylix handle theme via qtct
      # Don't override platformTheme.name as Stylix sets it to "qtct"
      qt = {
        enable = lib.mkDefault true;
        # style.name handled by Stylix
      };

      # Install theme packages
      home.packages = with pkgs; [
        # Theme packages
        adw-gtk3
        papirus-icon-theme
        vanilla-dmz

        # GTK settings tools
        lxappearance

        # dconf for virt-manager settings
        dconf
      ];

      # virt-manager specific settings via dconf
      dconf.settings = {
        "org/virt-manager/virt-manager" = {
          xmleditor-enabled = true;
        };

        "org/virt-manager/virt-manager/console" = {
          scaling = 2;  # Scale to fit
          resize-guest = 1;  # Auto-resize guest
        };

        "org/virt-manager/virt-manager/confirm" = {
          forcepoweroff = false;
          removedev = false;
          unapplied-dev = false;
        };

        "org/virt-manager/virt-manager/stats" = {
          enable-cpu-poll = true;
          enable-disk-poll = true;
          enable-memory-poll = true;
          enable-net-poll = true;
        };

        "org/virt-manager/virt-manager/vmlist-fields" = {
          cpu-usage = true;
          disk-usage = false;
          host-cpu-usage = true;
          memory-usage = true;
          network-traffic = true;
        };

        # GTK file chooser settings
        "org/gtk/settings/file-chooser" = {
          show-hidden = true;
          sort-directories-first = true;
          location-mode = "path-bar";
        };
      };
    };
  };
}
