# Base Image - Pre-built profile with instant first-boot
#
# Unlike minimal-base which runs nixos-rebuild on first boot,
# base images contain the COMPLETE system already built.
# First-boot only applies instance config (hostname, user, password).
#
# This makes VM deployment nearly instant (~5 seconds to boot + configure).
#
# Usage in flake.nix:
#   base-browsing = nixos-generators.nixosGenerate {
#     modules = [
#       ./profiles/browsing.nix
#       ./modules/vm/base-image.nix
#       { hydrix.vm.baseImage.enable = true; }
#     ];
#   };
#
{ config, lib, pkgs, ... }:

let
  cfg = config.hydrix.vm.baseImage;
  configMount = "/mnt/vm-config";
in
{
  options.hydrix.vm.baseImage = {
    enable = lib.mkEnableOption "base image VM with instant first-boot configuration";

    configMountTag = lib.mkOption {
      type = lib.types.str;
      default = "vm-config";
      description = "9p mount tag for VM instance config";
    };
  };

  config = lib.mkIf cfg.enable {
    # ============================================
    # FILESYSTEM - Config mount for instance data
    # ============================================

    # Mount VM instance config (hostname, username, password)
    fileSystems.${configMount} = {
      device = cfg.configMountTag;
      fsType = "9p";
      options = [
        "trans=virtio"
        "version=9p2000.L"
        "ro"
        "nofail"
        "x-systemd.automount"
      ];
      neededForBoot = false;
    };

    # ============================================
    # INSTANT FIRST-BOOT CONFIGURATION
    # ============================================

    # This service applies instance-specific config WITHOUT nixos-rebuild
    # It runs once on first boot, then never again
    systemd.services.vm-base-activate = {
      description = "Apply VM instance configuration (base image)";
      wantedBy = [ "multi-user.target" ];
      before = [ "display-manager.service" "getty@tty1.service" ];
      after = [ "local-fs.target" ];

      # Only run if not yet configured
      unitConfig = {
        ConditionPathExists = "!/var/lib/vm-configured";
      };

      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
      };

      script = ''
        set -euo pipefail

        echo "=== Base Image First-Boot Configuration ==="

        CONFIG_DIR="${configMount}"

        # Wait for config mount (automount may take a moment)
        for i in $(seq 1 10); do
          if [ -d "$CONFIG_DIR" ] && [ -f "$CONFIG_DIR/hostname" ]; then
            break
          fi
          echo "Waiting for config mount... ($i/10)"
          sleep 1
        done

        # --- Read config values ---
        NEW_HOSTNAME=""
        REQUESTED_USER=""

        if [ -f "$CONFIG_DIR/hostname" ]; then
          NEW_HOSTNAME=$(cat "$CONFIG_DIR/hostname")
        fi

        if [ -f "$CONFIG_DIR/username" ]; then
          REQUESTED_USER=$(cat "$CONFIG_DIR/username")
        fi

        # --- Apply Hostname ---
        if [ -n "$NEW_HOSTNAME" ]; then
          echo "Setting hostname: $NEW_HOSTNAME"
          ${pkgs.systemd}/bin/hostnamectl set-hostname "$NEW_HOSTNAME" || true
          ${pkgs.hostname}/bin/hostname "$NEW_HOSTNAME" || true
        fi

        # --- Update vm-instance.nix with BOTH hostname and username ---
        # This ensures future rebuilds pick up both values correctly
        for hydrix_dir in /home/*/hydrix-config; do
          if [ -d "$hydrix_dir/local" ]; then
            echo "Updating $hydrix_dir/local/vm-instance.nix"
            mkdir -p "$hydrix_dir/local"
            cat > "$hydrix_dir/local/vm-instance.nix" << EOF
# VM instance configuration (generated by first-boot)
# This file is regenerated on each VM deployment
{
  hostname = "$NEW_HOSTNAME";
  username = "$REQUESTED_USER";
}
EOF
            chown --reference="$hydrix_dir" "$hydrix_dir/local/vm-instance.nix" 2>/dev/null || true
            echo "  hostname=$NEW_HOSTNAME, username=$REQUESTED_USER"
          fi
        done

        # --- Check username mismatch ---
        if [ -n "$REQUESTED_USER" ]; then
          CURRENT_USER=$(id -un 1000 2>/dev/null || echo "user")
          if [ "$REQUESTED_USER" != "$CURRENT_USER" ]; then
            echo ""
            echo "NOTE: Requested username '$REQUESTED_USER' differs from baked username '$CURRENT_USER'"
            echo "      Run 'rebuild' in ~/hydrix-config to apply the new username"
            echo ""
          fi
        fi

        # Mark as configured
        mkdir -p /var/lib
        echo "configured" > /var/lib/vm-configured
        date >> /var/lib/vm-configured

        echo "=== Base image configuration complete ==="
      '';
    };

    # ============================================
    # BASE IMAGE DEFAULTS
    # ============================================

    # Default hostname (will be overridden by first-boot)
    networking.hostName = lib.mkDefault "base-vm";

    # Ensure services needed for first-boot config
    services.qemuGuest.enable = lib.mkDefault true;
    services.spice-vdagentd.enable = lib.mkDefault true;
  };
}
