# VM Base Module - Central configuration for all VMs (except router)
#
# This module consolidates all common VM configuration:
# - Hardware configuration (kernel modules, boot loader, filesystem)
# - Instance config loading (hostname from local/vm-instance.nix)
# - Shared locale loading (from local/shared.nix)
# - Common imports (qemu-guest, shared-store, bake-config, etc.)
# - Parameterized rebuild script
#
# Profiles should import this module and only set profile-specific config:
# - hydrix.vmType
# - hydrix.colorscheme
# - hydrix.vm.defaultHostname
# - Profile-specific packages and services
#
{ config, pkgs, lib, modulesPath, ... }:

let
  # Load instance config if it exists (generated by build-vm.sh)
  # This file is created at build time and baked into the image
  instanceConfigPath = ../../local/vm-instance.nix;
  instanceConfig =
    if builtins.pathExists instanceConfigPath
    then import instanceConfigPath
    else {};

  # Get hostname from instance config, or use default from options
  vmHostname = instanceConfig.hostname or config.hydrix.vm.defaultHostname;

  # Load shared config for locale settings (gitignored, generated by setup.sh)
  sharedConfigPath = ../../local/shared.nix;
  sharedConfig =
    if builtins.pathExists sharedConfigPath
    then import sharedConfigPath
    else {
      timezone = "UTC";
      locale = "en_US.UTF-8";
      consoleKeymap = "us";
      xkbLayout = "us";
      xkbVariant = "";
    };

  # Rebuild target for the script (e.g., "vm-pentest")
  rebuildTarget = config.hydrix.vm.rebuildTarget;

in {
  imports = [
    # QEMU guest profile from nixpkgs
    (modulesPath + "/profiles/qemu-guest.nix")

    # Base system modules
    ../base/nixos-base.nix
    ../base/users-vm.nix
    ../base/networking.nix

    # VM-specific modules
    ./qemu-guest.nix
    ./shared-store.nix
    ./bake-config.nix

    # Core desktop environment
    ../core.nix

    # Theming system
    ../theming/static-colors.nix
    ../desktop/xinitrc.nix

    # Firefox browser
    ../desktop/firefox.nix
  ];

  options.hydrix.vm = {
    defaultHostname = lib.mkOption {
      type = lib.types.str;
      default = "${config.hydrix.vmType or "unknown"}-vm";
      description = "Default hostname if local/vm-instance.nix doesn't exist";
    };

    rebuildTarget = lib.mkOption {
      type = lib.types.str;
      default = "vm-${config.hydrix.vmType or "unknown"}";
      description = "Flake target for rebuild script (e.g., vm-pentest)";
    };
  };

  config = {
    # ===== Hardware configuration for QEMU VMs =====
    # QEMU hardware is always the same - no hardware-configuration.nix needed
    boot.initrd.availableKernelModules = [
      "virtio_balloon" "virtio_blk" "virtio_pci" "virtio_ring"
      "virtio_net" "virtio_scsi" "virtio_console"
      "ahci" "xhci_pci" "sd_mod" "sr_mod"
    ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ "kvm-intel" "kvm-amd" ];
    boot.extraModulePackages = [ ];

    # Boot loader
    boot.loader.grub = {
      enable = true;
      device = lib.mkDefault "/dev/vda";
      efiSupport = false;
      useOSProber = false;
    };

    # Filesystem - nixos-generators creates disk with label "nixos"
    fileSystems."/" = lib.mkDefault {
      device = "/dev/disk/by-label/nixos";
      fsType = "ext4";
    };

    swapDevices = [ ];

    networking.useDHCP = lib.mkDefault true;
    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

    # ===== Hostname from instance config =====
    networking.hostName = lib.mkForce vmHostname;

    # ===== Locale settings from shared config =====
    time.timeZone = sharedConfig.timezone;
    i18n.defaultLocale = sharedConfig.locale;
    console.keyMap = sharedConfig.consoleKeymap;
    services.xserver.xkb.layout = sharedConfig.xkbLayout;
    services.xserver.xkb.variant = sharedConfig.xkbVariant or "";

    # ===== Enable virtiofs shared /nix/store =====
    hydrix.vm.sharedStore.enable = lib.mkDefault true;

    # ===== Rebuild script =====
    # Parameterized based on hydrix.vm.rebuildTarget
    environment.systemPackages = [
      (pkgs.writeShellScriptBin "rebuild" ''
        #!/usr/bin/env bash
        set -e
        cd ~/Hydrix
        echo "Rebuilding ${vmHostname}..."
        echo "Using flake target: ${rebuildTarget}"
        sudo nixos-rebuild switch --flake '.#${rebuildTarget}' --impure
      '')
    ];
  };
}
