# Example Machine Configuration
#
# Machine configs are named by HARDWARE SERIAL (detected automatically).
# Copy this file and rename it to your hardware serial (e.g., abc123def.nix).
#
# To find your serial:
#   cat /sys/class/dmi/id/product_serial
#   # or: sudo dmidecode -s system-serial-number
#
# The rebuild script auto-detects your machine serial, so you can just run:
#   rebuild                    # Uses detected serial
#   rebuild administrative     # Admin mode
#   rebuild fallback           # Fallback mode
#
# Manual build (if needed):
#   sudo nixos-rebuild switch --flake .#<serial>
#
# ═══════════════════════════════════════════════════════════════════════════
# BOOT MODES
# ═══════════════════════════════════════════════════════════════════════════
#
#   DEFAULT (Lockdown):  No host internet, minimal packages, hardened
#   Administrative:      Full functionality, router VM, all packages
#   Fallback:            Emergency direct WiFi, no VMs
#
# Switch modes:
#   sudo nixos-rebuild switch                                    # → Lockdown
#   sudo nixos-rebuild switch --specialisation administrative   # → Admin
#   sudo nixos-rebuild switch --specialisation fallback         # → Fallback
#
# Or select at boot from GRUB menu.
# ═══════════════════════════════════════════════════════════════════════════

{ config, lib, pkgs, ... }:

{
  # =========================================================================
  # SPECIALISATIONS
  # =========================================================================
  # The Hydrix framework defines the infrastructure for each mode:
  #   - Base config = LOCKDOWN (no host internet, builder VM for builds)
  #   - Administrative = adds gateway, libvirtd, full packages
  #   - Fallback = emergency direct WiFi (requires reboot)
  #
  # The files below are for YOUR extra packages/settings per mode.
  # You can safely leave them empty or add packages as needed.

  imports = [
    # IMPORTANT: Import your hardware config (generated by the setup script)
    # ./YOUR-SERIAL-hardware.nix
    # Base packages (available in ALL modes)
    ../specialisations/lockdown.nix
  ];

  # Administrative mode - your extra packages
  specialisation.administrative.configuration = {
    imports = [ ../specialisations/administrative.nix ];
  };

  # Fallback mode - your extra packages
  specialisation.fallback.configuration = {
    imports = [ ../specialisations/fallback.nix ];
  };

  # Custom modes: uncomment to add your own specialisation
  # specialisation.leisure.configuration = {
  #   imports = [ ../specialisations/leisure.nix ];
  # };

  # =========================================================================
  # USER CREDENTIALS (Optional)
  # =========================================================================
  # By default, your existing password is preserved from /etc/shadow.
  # Only set this if you want to manage password declaratively:
  #
  # hydrix.user.hashedPassword = "$6$...";  # Generate with: mkpasswd -m sha-512

  # =========================================================================
  # HYDRIX CONFIGURATION
  # =========================================================================
  hydrix = {
    # ─────────────────────────────────────────────────────────────────────
    # IDENTITY
    # ─────────────────────────────────────────────────────────────────────
    username = "user";           # Your username
    hostname = "hydrix";         # Visual hostname (config file identified by serial)
    colorscheme = "nord";        # Theme (see colorschemes/ in Hydrix repo)

    # ─────────────────────────────────────────────────────────────────────
    # LOCALE
    # ─────────────────────────────────────────────────────────────────────
    locale = {
      timezone = "UTC";
      language = "en_US.UTF-8";
      consoleKeymap = "us";
      xkbLayout = "us";
      xkbVariant = "";
    };

    # ─────────────────────────────────────────────────────────────────────
    # DISKO - Disk Partitioning (only for fresh installs)
    # ─────────────────────────────────────────────────────────────────────
    disko = {
      enable = true;
      device = "/dev/nvme0n1";
      swapSize = "16G";
      layout = "full-disk-plain";  # full-disk-plain, full-disk-luks, dual-boot-luks
    };

    # ─────────────────────────────────────────────────────────────────────
    # ROUTER
    # ─────────────────────────────────────────────────────────────────────
    # WiFi credentials are in shared/wifi.nix (shared across all machines)
    router = {
      type = "microvm";  # "microvm" (recommended), "libvirt", or "none"
      autostart = true;  # Start router VM automatically
    };

    # ─────────────────────────────────────────────────────────────────────
    # HARDWARE
    # ─────────────────────────────────────────────────────────────────────
    hardware = {
      platform = "intel";  # "intel", "amd", or "generic"
      isAsus = false;      # Set true for ASUS laptops

      vfio = {
        enable = true;
        pciIds = [ "8086:a840" ];      # Your WiFi card's vendor:device ID
        wifiPciAddress = "00:14.3";    # Your WiFi card's PCI address
      };

      # bluetooth.enable = true;     # DEFAULT: true - Bluetooth + Blueman
      # i2c.enable = true;           # DEFAULT: true - DDC/CI monitor control
      # touchpad.enable = true;      # DEFAULT: true - libinput touchpad

      grub.gfxmodeEfi = "1920x1200";   # Your display resolution for GRUB
    };

    # ─────────────────────────────────────────────────────────────────────
    # POWER
    # ─────────────────────────────────────────────────────────────────────
    power = {
      defaultProfile = "balanced";  # "powersave", "balanced", "performance"
      # chargeLimit = 60;           # Battery charge limit (20-100, preserves battery)
      # autoCpuFreq = true;          # DEFAULT: true - auto-cpufreq service
    };

    # ─────────────────────────────────────────────────────────────────────
    # SERVICES
    # ─────────────────────────────────────────────────────────────────────
    # services = {
    #   tailscale.enable = false;     # DEFAULT: false - Tailscale VPN
    #   ssh.enable = true;            # DEFAULT: true - OpenSSH daemon
    # };

    # ─────────────────────────────────────────────────────────────────────
    # SECRETS (optional - for GitHub SSH keys, etc.)
    # ─────────────────────────────────────────────────────────────────────
    secrets = {
      enable = false;
      github.enable = false;
    };

    # ─────────────────────────────────────────────────────────────────────
    # MICROVM HOST
    # ─────────────────────────────────────────────────────────────────────
    microvmHost = {
      enable = true;
      vms = {
        "microvm-router".enable = true;
        "microvm-router".autostart = true;
        "microvm-browsing".enable = true;
        "microvm-pentest".enable = true;
        "microvm-dev".enable = true;
        "microvm-comms".enable = true;
        "microvm-lurking".enable = true;
        "microvm-builder".enable = true;
        "microvm-gitsync".enable = true;
      };
    };

    # ─────────────────────────────────────────────────────────────────────
    # BUILDER (for lockdown mode nix builds)
    # ─────────────────────────────────────────────────────────────────────
    builder.enable = true;

    # ─────────────────────────────────────────────────────────────────────
    # GIT-SYNC (for lockdown mode git push/pull)
    # ─────────────────────────────────────────────────────────────────────
    gitsync.enable = true;

    # ─────────────────────────────────────────────────────────────────────
    # GRAPHICAL
    # ─────────────────────────────────────────────────────────────────────
    # Defaults are set by font profiles (iosevka, tamzen, cozette).
    # Only override what you need to customize.
    graphical = {
      enable = true;
      # font.family = "Iosevka";              # Font profile auto-selected
      # font.size = 10;                       # Override base size
      # ui.gaps = 10;                         # Window gaps (default: 15)
      # ui.barGaps = 5;                       # Bar-to-screen-edge gap (default: gaps/2)
      # ui.barHeight = 23;                    # Bar height (default: 23)
      # ui.barPadding = 2;                    # Padding inside bar (default: 2)
      # ui.border = 2;                        # Window border width (default: 2)
      # ui.polybarStyle = "unibar";           # unibar, modular, pills
      # bluelight.autoRestart = false;              # DEFAULT: false - only starts on boot
      # scaling.internalResolution = "1920x1200";  # For HiDPI laptops
      # keyboard.xmodmap = ''
      #   clear lock
      #   clear control
      #   keycode 66 = Control_L
      #   add control = Control_L Control_R
      # '';
    };
  };
}
