# Example Machine Configuration
#
# Machine configs are named by HARDWARE SERIAL (detected automatically).
# Copy this file and rename it to your hardware serial (e.g., abc123def.nix).
#
# To find your serial:
#   cat /sys/class/dmi/id/product_serial
#   # or: sudo dmidecode -s system-serial-number
#
# The rebuild script auto-detects your machine serial, so you can just run:
#   rebuild                    # Uses detected serial
#   rebuild administrative     # Admin mode
#   rebuild fallback           # Fallback mode
#
# Manual build (if needed):
#   sudo nixos-rebuild switch --flake .#<serial>
#
# ═══════════════════════════════════════════════════════════════════════════
# BOOT MODES
# ═══════════════════════════════════════════════════════════════════════════
#
#   DEFAULT (Lockdown):  No host internet, minimal packages, hardened
#   Administrative:      Full functionality, router VM, all packages
#   Fallback:            Emergency direct WiFi, no VMs
#
# Switch modes:
#   sudo nixos-rebuild switch                                    # → Lockdown
#   sudo nixos-rebuild switch --specialisation administrative   # → Admin
#   sudo nixos-rebuild switch --specialisation fallback         # → Fallback
#
# Or select at boot from GRUB menu.
# ═══════════════════════════════════════════════════════════════════════════

{ config, lib, pkgs, hydrix, ... }:

{
  # =========================================================================
  # SPECIALISATIONS
  # =========================================================================
  # The Hydrix framework defines the infrastructure for each mode:
  #   - Base config = LOCKDOWN (no host internet, builder VM for builds)
  #   - Administrative = adds gateway, libvirtd, full packages
  #   - Fallback = emergency direct WiFi (requires reboot)
  #
  # The files below are for YOUR extra packages/settings per mode.
  # You can safely leave them empty or add packages as needed.

  imports = [
    # IMPORTANT: Import your hardware config (generated by the setup script)
    # ./YOUR-SERIAL-hardware.nix
    # Base packages (available in ALL modes)
    ../specialisations/lockdown.nix
  ];

  # Administrative mode - your extra packages
  specialisation.administrative.configuration = {
    imports = [ ../specialisations/administrative.nix ];
  };

  # Fallback mode - your extra packages
  specialisation.fallback.configuration = {
    imports = [ ../specialisations/fallback.nix ];
  };

  # Custom modes: uncomment to add your own specialisation
  # specialisation.leisure.configuration = {
  #   imports = [ ../specialisations/leisure.nix ];
  # };

  # =========================================================================
  # USER CREDENTIALS (Optional)
  # =========================================================================
  # By default, your existing password is preserved from /etc/shadow.
  # Only set this if you want to manage password declaratively:
  #
  # hydrix.user.hashedPassword = "$6$...";  # Generate with: mkpasswd -m sha-512

  # Auto-login on console (default: false on host, true in VMs)
  # hydrix.user.autologin = true;

  # SSH public keys for authorized_keys (optional)
  # hydrix.user.sshPublicKeys = [
  #   "ssh-ed25519 AAAA... user@host"
  # ];

  # Extra groups beyond defaults (wheel, audio, video, etc.)
  # hydrix.user.extraGroups = [ "libvirtd" "kvm" ];

  # Display name shown in finger, etc. (defaults to username)
  # hydrix.user.description = "Jane Doe";

  # =========================================================================
  # HYDRIX CONFIGURATION
  # =========================================================================
  hydrix = {
    # ─────────────────────────────────────────────────────────────────────
    # IDENTITY
    # ─────────────────────────────────────────────────────────────────────
    username = "user";           # Your username
    hostname = "hydrix";         # Visual hostname (config file identified by serial)
    colorscheme = "puccy";       # Theme (see colorschemes/ in Hydrix repo)
    graphical.wallpaper = "${hydrix}/wallpapers/WindowRain.png";  # Default wallpaper (nix store path)
    # vmThemeSync.focusDaemon.mode = "dynamic";  # "static" or "dynamic" focus border colors

    # ─────────────────────────────────────────────────────────────────────
    # PATHS
    # ─────────────────────────────────────────────────────────────────────
    # Baked into scripts at build time. Only override if your repos are not
    # in the standard locations (~/hydrix-config, ~/Hydrix).
    # paths.configDir = "/home/user/hydrix-config";  # DEFAULT: ~/hydrix-config
    # paths.hydrixDir = "/home/user/Hydrix";         # DEFAULT: ~/Hydrix

    # ─────────────────────────────────────────────────────────────────────
    # DEFAULT APPLICATIONS
    # ─────────────────────────────────────────────────────────────────────
    # These values are used throughout the graphical environment (i3, scripts, etc.)
    # Change them to substitute different programs - the framework references these
    # names rather than hardcoding specific apps.
    #
    # terminal = "alacritty";   # DEFAULT: alacritty
    # shell    = "fish";        # DEFAULT: fish  (options: fish, bash, zsh)
    # browser  = "firefox";     # DEFAULT: firefox
    # editor   = "vim";         # DEFAULT: vim
    # fileManager  = "ranger";  # DEFAULT: ranger
    # imageViewer  = "feh";     # DEFAULT: feh
    # mediaPlayer  = "mpv";     # DEFAULT: mpv
    # pdfViewer    = "zathura"; # DEFAULT: zathura

    # ─────────────────────────────────────────────────────────────────────
    # LOCALE
    # ─────────────────────────────────────────────────────────────────────
    locale = {
      timezone = "UTC";
      language = "en_US.UTF-8";
      consoleKeymap = "us";
      xkbLayout = "us";
      xkbVariant = "";
    };

    # ─────────────────────────────────────────────────────────────────────
    # DISKO - Disk Partitioning (only for fresh installs)
    # ─────────────────────────────────────────────────────────────────────
    disko = {
      enable = true;
      device = "/dev/nvme0n1";  # Run: lsblk -d to find your disk
      swapSize = "16G";         # Match your RAM, or half for hibernation

      # Layout options:
      # ┌─────────────────────┬──────────────────────────────────────────────┐
      # │ full-disk-plain     │ BTRFS, no encryption (fastest, simplest)     │
      # │ full-disk-luks      │ BTRFS + LUKS full-disk encryption            │
      # │ dual-boot-luks      │ Preserve existing EFI + LUKS for NixOS part  │
      # │ dual-boot-plain     │ Preserve existing EFI, no encryption         │
      # └─────────────────────┴──────────────────────────────────────────────┘
      # LUKS password is prompted interactively at install — never stored here.
      layout = "full-disk-plain";

      # Dual-boot only: set by the installer, do not edit manually.
      # nixosPartition is the pre-created NixOS partition disko will format.
      # efiPartition is the existing Windows/Linux EFI partition to reuse for /boot.
      # nixosPartition = "";
      # efiPartition = "";
    };

    # ─────────────────────────────────────────────────────────────────────
    # ROUTER
    # ─────────────────────────────────────────────────────────────────────
    # WiFi credentials are in shared/wifi.nix (shared across all machines).
    router = {
      type = "microvm";  # "microvm" (recommended), "libvirt", or "none"
      autostart = true;  # Start router VM automatically

      # ─── Mullvad VPN (optional) ────────────────────────────────────────
      # Copy vpn/mullvad.nix.example to vpn/mullvad.nix, fill in your
      # credentials from https://mullvad.net/account → WireGuard, then:
      #
      # vpn.mullvad = import ../vpn/mullvad.nix;
      #
      # Each exitNode in mullvad.nix becomes a WireGuard interface on the router.
      # Assign VM bridges to exit nodes at runtime:
      #   vpn-assign browse mullvad-se                   # Route browsing via Sweden
      #   vpn-assign lurking mullvad-ch                  # Route lurking via Switzerland
      #   vpn-assign --persistent comms mullvad-de       # Persist assignment across reboots
      #   vpn-assign pentest none                        # Direct (no VPN) for engagements

      # ─── Router VM user (microvm router) ─────────────────────────────
      # username       = "user";   # DEFAULT: inherits hydrix.username
      # hashedPassword = null;     # DEFAULT: null (inherits host password if set)

      # ─── Multi-network WiFi (alternative to shared/wifi.nix) ──────────
      # wifi.networks = [
      #   { ssid = "HomeNetwork"; password = "secret"; priority = 100; }
      #   { ssid = "WorkNetwork"; password = "secret2"; priority = 50; }
      # ];
      # (Takes precedence over wifi.ssid/password if non-empty)

      # ─── libvirt router (if type = "libvirt") ──────────────────────────
      # router.libvirt.vmName  = "router";        # DEFAULT: "router"
      # router.libvirt.image   = "/var/lib/libvirt/images/router.qcow2";  # DEFAULT
      # router.libvirt.memory  = 2048;            # DEFAULT: 2048 MB
      # router.libvirt.vcpus   = 2;               # DEFAULT: 2
      # router.libvirt.wan.mode = "auto";         # DEFAULT: "auto"
      #   # Options: "auto" (detects WiFi for passthrough, falls back to macvtap)
      #   #          "pci-passthrough", "macvtap", "none"
      # router.libvirt.wan.device = null;         # DEFAULT: null (auto-detect)
      #   # pci-passthrough: PCI address e.g. "0000:02:00.0"
      #   # macvtap: interface name e.g. "enp3s0"
      # router.libvirt.wan.preferWireless = true; # DEFAULT: true - prefer WiFi over ethernet in auto mode
    };

    # ─────────────────────────────────────────────────────────────────────
    # HARDWARE
    # ─────────────────────────────────────────────────────────────────────
    hardware = {
      platform = "intel";  # "intel"   → intel-microcode, iommu=pt for VFIO, VA-API drivers
                           # "amd"     → amd-microcode (TODO: amd.nix needs iommu params,
                           #              VA-API drivers and power management parity with intel.nix)
                           # "generic" → no vendor microcode, generic IOMMU
      isAsus = false;      # true → enables asus-linux (asusctl, supergfxctl, ROG features)
                           #        required for ASUS audio (cs42l43), keyboard backlight, fan curves

      vfio = {
        enable = true;
        pciIds = [ "8086:a840" ];      # Your WiFi card's vendor:device ID
        wifiPciAddress = "00:14.3";    # Your WiFi card's PCI address
      };

      # bluetooth.enable = true;     # DEFAULT: true - Bluetooth + Blueman
      # i2c.enable = true;           # DEFAULT: true - DDC/CI monitor control
      # touchpad.enable = true;      # DEFAULT: true - libinput touchpad

      grub.gfxmodeEfi = "1920x1200";   # Your display resolution for GRUB
    };

    # ─────────────────────────────────────────────────────────────────────
    # POWER
    # ─────────────────────────────────────────────────────────────────────
    power = {
      defaultProfile = "balanced";  # "powersave", "balanced", "performance"
      # chargeLimit = 60;           # Battery charge limit (20-100, preserves battery)
      # autoCpuFreq = true;         # DEFAULT: true - auto-cpufreq service
    };

    # ─────────────────────────────────────────────────────────────────────
    # SERVICES
    # ─────────────────────────────────────────────────────────────────────
    # Host-level Hydrix-managed service toggles.
    # VM-level services (Docker, MariaDB, Tor, PostgreSQL) are NixOS options
    # set directly in the relevant profile (profiles/<name>/default.nix).
    #
    # services = {
    #   tailscale.enable = true;   # DEFAULT: true  - Tailscale VPN mesh
    #   ssh.enable = true;         # DEFAULT: true  - OpenSSH daemon
    # };

    # ─────────────────────────────────────────────────────────────────────
    # LIBVIRT (only needed if using libvirt router or virt-manager)
    # ─────────────────────────────────────────────────────────────────────
    # libvirt.enable = false;  # DEFAULT: false
    #                          # Auto-enabled when router.type = "libvirt"
    #                          # Set manually if you need virt-manager/QEMU on host

    # ─────────────────────────────────────────────────────────────────────
    # SECRETS (optional - for GitHub SSH keys, etc.)
    # ─────────────────────────────────────────────────────────────────────
    # Setup workflow:
    #   1. Rebuild once (generates /etc/ssh/ssh_host_ed25519_key)
    #   2. Run: sops-age-pubkey          (prints your age public key)
    #   3. Add key to secrets/.sops.yaml (see that file in this repo)
    #   4. Fill in secrets/github.yaml.example → secrets/github.yaml
    #      then encrypt: sops -e -i secrets/github.yaml
    #   5. Set enable = true + github.enable = true, then rebuild
    #
    # When github.enable = true, /run/secrets/github/id_ed25519 is available at boot.
    # VMs with secrets.github = true (in microvmHost.vms) get the key provisioned
    # into their home directory at startup.
    secrets = {
      enable = false;
      github.enable = false;
    };

    # ─────────────────────────────────────────────────────────────────────
    # MICROVM HOST
    # ─────────────────────────────────────────────────────────────────────
    microvmHost = {
      enable = true;
      vms = {
        "microvm-router"   = { enable = true; autostart = true; };
        "microvm-browsing" = { enable = true; /* secrets.github = true; */ };
        "microvm-pentest"  = { enable = true; /* secrets.github = true; */ };
        "microvm-dev"      = { enable = true; secrets.github = true; };  # git push/pull inside VM
        "microvm-comms"    = { enable = true; /* secrets.github = true; */ };
        "microvm-lurking"  = { enable = true; };  # ephemeral - privacy-first
        "microvm-builder"  = { enable = true; /* secrets.github = true; */ };
        "microvm-gitsync"  = { enable = true; };  # uses host sops key, not VM secrets
      };
      # secrets.github = true  requires: secrets.github.enable = true (above)
      # autostart = true       starts VM at boot (default: false — start manually)

      # Custom VM names (change what the systemd units are called)
      # vmNames.browse  = "microvm-browsing";  # DEFAULT
      # vmNames.hack    = "microvm-pentest";   # DEFAULT
      # vmNames.dev     = "microvm-dev";       # DEFAULT
      # vmNames.comms   = "microvm-comms";     # DEFAULT
      # vmNames.lurk    = "microvm-lurking";   # DEFAULT
      # vmNames.build   = "microvm-builder";   # DEFAULT
      # vmNames.router  = "microvm-router";    # DEFAULT
      # vmNames.gitsync = "microvm-gitsync";   # DEFAULT

      # defaultBridge = "br-browse";  # DEFAULT: br-browse
      #   Fallback bridge for TAP interfaces with no explicit bridge assignment.
    };

    # ─────────────────────────────────────────────────────────────────────
    # BUILDER (lockdown mode nix builds via microvm-builder)
    # ─────────────────────────────────────────────────────────────────────
    # Enables host nix-daemon stop/start and /nix/store R/W remount.
    # Builder VM is declared in flake.nix → mkMicrovmBuilder { ... }
    # Usage: microvm builder build browsing
    #        microvm builder switch
    builder.enable = true;

    # ─────────────────────────────────────────────────────────────────────
    # GIT-SYNC (lockdown mode git push/pull via microvm-gitsync)
    # ─────────────────────────────────────────────────────────────────────
    # Repos are declared in flake.nix → mkMicrovmGitSync { repos = [...]; }
    # Each repo is mounted R/W into the VM at /mnt/repos/<name>
    # Usage: microvm console microvm-gitsync
    #        → cd /mnt/repos/hydrix-config && git push
    gitsync.enable = true;

    # ─────────────────────────────────────────────────────────────────────
    # GRAPHICAL
    # ─────────────────────────────────────────────────────────────────────
    # Shared UI preferences live in shared/graphical.nix (imported for all machines).
    # Uncomment anything here to override the shared value for this machine only —
    # plain assignment takes priority over lib.mkDefault in the shared module.
    graphical = {
      enable = true;

      # polarity = "dark";  # DEFAULT: "dark" - color scheme polarity ("dark" or "light")

      # colorscheme = "nord";  # DEFAULT: inherits hydrix.colorscheme
      #   Override the graphical colorscheme independently of the system colorscheme.

      # standalone = false;  # DEFAULT: false
      #   Enable a full i3/polybar environment inside this VM (for use with virt-manager).
      #   Default false = headless, apps forwarded to host via xpra.

      # ─── Applications ────────────────────────────────────────────────
      # firefox.hostEnable  = false;  # DEFAULT: false - Firefox on host (admin mode sets this)
      # firefox.userAgent   = null;   # DEFAULT: null (real Firefox UA)
      #   Lock a spoofed UA via policy. Named presets: "edge-windows", "chrome-windows",
      #   "chrome-mac", "safari-mac", "firefox-windows". Or pass a raw UA string.
      # obsidian.hostEnable = false;  # DEFAULT: false - Obsidian on host
      # obsidian.vaultPaths = [];     # e.g. [ "notes" "projects" ] — deploys CSS to each vault

      # ─── Font ────────────────────────────────────────────────────────
      # font.family = "Iosevka";      # Font profile auto-selected
      # font.size   = 10;             # Override base size
      # font.overrides = { alacritty = 10.5; };  # Direct per-app size override (bypasses DPI scaling)
      # font.maxSizes  = { alacritty = 10.5; polybar = 13; };  # Per-app size cap
      # font.standaloneRelations = { alacritty = 1.05; };  # Per-app multipliers when no external monitor
      #   Falls back to font.relations for apps not listed here.
      # font.familyOverrides = { alacritty = "Tamzen"; };  # Per-app font family override

      # ─── UI layout ───────────────────────────────────────────────────
      # ui.gaps        = 15;          # DEFAULT: 15 - i3 inner gaps
      # ui.barGaps     = null;        # DEFAULT: gaps/2 - polybar float margin (null = auto)
      # ui.barHeight   = 23;          # DEFAULT: 23 - polybar height
      # ui.barHeightRelation = 1.0;   # DEFAULT: 1.0 - bar height multiplier (applied after DPI scaling)
      # ui.barPadding  = 2;           # DEFAULT: 2  - padding inside bar
      # ui.border      = 2;           # DEFAULT: 2  - window border width
      # ui.floatingBar = true;        # DEFAULT: true  - floating polybar
      # ui.bottomBar   = true;        # DEFAULT: true  - bottom bar with VM metrics
      # ui.polybarStyle = "modular";  # DEFAULT: "modular" - unibar, modular, pills
      # ui.cornerRadius = 2;          # DEFAULT: 2  - picom corner radius

      # ─── Workspace labels ────────────────────────────────────────────
      # Default labels are roman numerals: I, II, III ... X
      # ui.workspaceLabels = { "1" = "web"; "2" = "code"; "3" = "term"; };
      # ui.workspaceDescriptions = { "1" = "browsing"; "2" = "dev"; };

      # ─── Opacity / transparency ──────────────────────────────────────
      # ui.opacity.overlay         = 0.85;   # DEFAULT: 0.85 - terminals and overlay elements
      # ui.opacity.overlayOverrides = { alacritty = 0.95; };  # Per-app overrides
      # ui.opacity.active          = 1.0;    # DEFAULT: 1.0 - active window
      # ui.opacity.inactive        = 1.0;    # DEFAULT: 1.0 - inactive window

      # ─── Compositor (picom) ──────────────────────────────────────────
      # ui.compositor.animations = "modern";  # DEFAULT: "modern" - "none" or "modern"
      # ui.shadowRadius = 18;          # DEFAULT: 18 - picom shadow size
      # ui.shadowOffset = 17;          # DEFAULT: 17 - picom shadow position offset
      # ui.polybarFontOffset = 3;      # DEFAULT: 3  - vertical text centering in bar
      # ui.rofiWidth  = 800;           # DEFAULT: 800 - launcher window width (px)
      # ui.rofiHeight = 400;           # DEFAULT: 400 - launcher window height (px)
      # ui.dunstWidth  = 300;          # DEFAULT: 300 - notification popup width (px)
      # ui.dunstOffset = 300;          # DEFAULT: 300 - notification edge offset (px)
      # ui.dunstSound  = true;         # DEFAULT: true - play sound on notifications
      # ui.outerGapsMatchBar = false;  # DEFAULT: false - match outer i3 gaps to bar margins
      # ui.barEdgeGapsFactor = 1.0;    # DEFAULT: 1.0 - bar-to-screen-edge gap multiplier
      # ui.gapsStandaloneRelation = 1.0;  # DEFAULT: 1.0 - gap multiplier without external monitor

      # ─── Bar module layout ────────────────────────────────────────────
      # Override which modules appear in each position. null = style default.
      # Available modules depend on polybarStyle — modular uses *-dynamic variants.
      #
      # ui.bar.top.left   = null;  # DEFAULT: "xworkspaces [workspace-desc] focus[-dynamic]"
      # ui.bar.top.center = null;  # DEFAULT: "" (empty)
      # ui.bar.top.right  = null;  # DEFAULT: metrics + date (style-dependent)
      #   e.g. "volume-dynamic cpu-dynamic ram-dynamic date-dynamic"
      #
      # ui.bar.bottom.left   = null;  # DEFAULT: "power-profile-dynamic battery-dynamic ..."
      # ui.bar.bottom.center = null;  # DEFAULT: "" (empty)
      # ui.bar.bottom.right  = null;  # DEFAULT: VM metrics (ram, cpu, fs, tun, net)

      # ─── Keyboard remapping ──────────────────────────────────────────
      # keyboard.xmodmap = ''
      #   # CapsLock → Ctrl (common remapping)
      #   clear lock
      #   clear control
      #   keycode 66 = Control_L
      #   add control = Control_L Control_R
      #
      #   # Remap key 49 to tilde/backtick (common on SE/Nordic layouts)
      #   # keycode 49 = asciitilde grave asciitilde grave
      # '';

      # ─── Blue light filter (blugon) ──────────────────────────────────
      # bluelight.enable       = true;   # DEFAULT: true
      # bluelight.defaultTemp  = 4500;   # DEFAULT: 4500K - manual temperature
      # bluelight.autoRestart  = false;  # DEFAULT: false - only starts on boot
      #
      # Time-based auto schedule (when autoRestart = true):
      # bluelight.schedule.dayTemp   = 6500;  # DEFAULT: 6500K - daytime temperature
      # bluelight.schedule.nightTemp = 3500;  # DEFAULT: 3500K - nighttime temperature
      # bluelight.schedule.dayStart  = 7;     # DEFAULT: 7 - hour daytime begins (0-23)
      # bluelight.schedule.nightStart = 20;   # DEFAULT: 20 - hour nighttime begins (0-23)

      # ─── HiDPI scaling ───────────────────────────────────────────────
      # scaling.internalResolution = "1920x1200";  # Native panel resolution
      #                                            # Find yours: xrandr | grep connected
      # scaling.auto = true;             # DEFAULT: true  - auto-detect connected display DPI
      # scaling.applyOnLogin = true;     # DEFAULT: true  - xrandr --auto on session start
      # scaling.referenceDpi = 96;       # DEFAULT: 96    - base DPI (96 = 100% scale)
      # scaling.standaloneScaleFactor = 1.0;  # DEFAULT: 1.0 - override when no external monitor

      # ─── Lockscreen ──────────────────────────────────────────────────
      # lockscreen = {
      #   idleTimeout = 600;                                              # DEFAULT: 600 (seconds, null to disable)
      #   font        = "CozetteVector";                                  # DEFAULT: "CozetteVector"
      #   fontSize    = 143;                                              # DEFAULT: 143
      #   clockSize   = 104;                                              # DEFAULT: 104
      #   text        = "Papers, please";                                 # DEFAULT: "Papers, please"
      #   wrongText   = "Ah ah ah! You didn't say the magic word!!";      # DEFAULT
      #   verifyText  = "Verifying...";                                   # DEFAULT
      #   blur        = true;                                             # DEFAULT: true
      # };

      # ─── Startup splash screen ───────────────────────────────────────
      # Displays a brief branded splash while the desktop loads.
      # splash = {
      #   enable   = false;          # DEFAULT: false - enable splash on login
      #   title    = "HYDRIX";       # DEFAULT: "HYDRIX"
      #   text     = "initializing...";  # DEFAULT
      #   maxTimeout = 15;           # DEFAULT: 15s safety timeout
      # };
    };

    # ─────────────────────────────────────────────────────────────────────
    # VM COLOR INHERITANCE
    # ─────────────────────────────────────────────────────────────────────
    # Set in shared/graphical.nix for all machines. Uncomment to override here.
    # colorschemeInheritance = "dynamic";  # "full", "dynamic", "none"

    # vmColors.hostColorscheme = null;  # Override host colorscheme used for VM inheritance

    # ─────────────────────────────────────────────────────────────────────
    # NETWORKING (advanced - defaults work for most setups)
    # ─────────────────────────────────────────────────────────────────────
    # Uncomment to override shared defaults for this machine only.
    # Only needed if you have IP conflicts on your LAN or require custom subnets.
    #
    # networking = {
    #   hostIp   = "192.168.100.1";    # DEFAULT: Host IP on management bridge
    #   routerIp = "192.168.100.253";  # DEFAULT: Router VM gateway IP
    #   subnets  = {
    #     mgmt    = "192.168.100";
    #     pentest = "192.168.101";
    #     comms   = "192.168.102";
    #     browse  = "192.168.103";
    #     dev     = "192.168.104";
    #     shared  = "192.168.105";
    #     builder = "192.168.106";
    #     lurking = "192.168.107";
    #   };
    # };

    # ─────────────────────────────────────────────────────────────────────
    # EXTRA VM NETWORKS
    # ─────────────────────────────────────────────────────────────────────
    # Declare additional VM networks beyond the built-in set.
    # Each entry creates: a host bridge (br-<name>), udev TAP rules, and a
    # router subnet with DHCP. Declare in flake.nix extraNetworks (preferred)
    # so the router VM picks them up automatically — or here for machine-specific networks.
    #
    # networking.extraNetworks = [
    #   { name = "office"; subnet = "192.168.109"; routerTap = "mv-router-offi"; }
    # ];

    # ─────────────────────────────────────────────────────────────────────
    # FILES VM
    # ─────────────────────────────────────────────────────────────────────
    # Encrypted inter-VM file transfer via microvm-files (CID 212).
    # Grant it direct L2 access to specific VM bridges.
    # See: README → Files VM (Encrypted Inter-VM Transfer)
    #
    # microvmFiles.enable = true;
    # microvmFiles.accessFrom = [ "pentest" "dev" "browsing" ];
    #   # Options: "mgmt" "pentest" "comms" "browsing" "dev" "shared" "lurking"
  };
}
