# Machine Configuration
# Serial: @SERIAL@
# Generated by Hydrix installer on @DATE@
#
# Config file is named by hardware serial for automatic reinstall detection.
# The visual hostname is always "hydrix".
#
# See machines/example-serial.nix for all available options with documentation.
#
# BOOT MODES:
#   DEFAULT (Lockdown):  No host internet, minimal packages, hardened
#   Administrative:      Full functionality, router VM, all packages
#   Fallback:            Emergency direct WiFi, no VMs
#
# Switch modes (rebuild script auto-detects this machine by serial):
#   rebuild                    -> Lockdown
#   rebuild administrative     -> Admin
#   rebuild fallback           -> Fallback

{ config, lib, pkgs, hydrix, ... }:

{
  imports = [
    ./@SERIAL@-hardware.nix
    ../specialisations/lockdown.nix
    ./grub-entries.nix
  ];

  specialisation.administrative.configuration = {
    imports = [ ../specialisations/administrative.nix ];
  };

  specialisation.fallback.configuration = {
    imports = [ ../specialisations/fallback.nix ];
  };

  users.users.@USERNAME@.hashedPassword = "@PASSWORD_HASH@";

  hydrix = {
    vmType = "host";
    username = "@USERNAME@";
    hostname = "hydrix";
    colorscheme = "@COLORSCHEME@";
    graphical.wallpaper = "${hydrix}/wallpapers/WindowRain.png";

    disko = {
      enable = true;
      device = "@DEVICE@";
      swapSize = "@SWAP_SIZE@";
      layout = "@LAYOUT@";
      nixosPartition = "@NIXOS_PARTITION@";
      efiPartition = "@EFI_PARTITION@";
      efiBootloaderId = "@EFI_BOOTLOADER_ID@";
    };

    router = {
      type = "@ROUTER_TYPE@";
      autostart = true;
    };

    hardware = {
      platform = "@PLATFORM@";
      isAsus = @IS_ASUS@;
      vfio = {
        enable = true;
        pciIds = [ "@WIFI_PCI_ID@" ];
        wifiPciAddress = "@WIFI_PCI_ADDRESS@";
      };
      grub.gfxmodeEfi = "@GRUB_GFXMODE@";
    };

    services = {
      ssh.enable = true;
    };

    power = {
      autoCpuFreq = true;
    };

    secrets = {
      enable = false;
      github.enable = false;
    };

    microvmHost = {
      enable = true;
      infrastructureOnly = true;  # Removed after install — first rebuild builds all VMs
      vms = {
        "microvm-router".enable    = true;
        "microvm-router".autostart = true;
        "microvm-browsing".enable  = true;
        "microvm-pentest".enable   = false;
        "microvm-dev".enable       = false;
        "microvm-comms".enable     = false;
        "microvm-lurking".enable   = false;
        "microvm-builder".enable   = true;
        "microvm-gitsync".enable   = true;
      };
    };

    builder.enable = true;
    gitsync.enable = true;

    graphical = {
      enable = true;
      font = { family = "Iosevka"; size = 10; };
      ui = { gaps = 10; floatingBar = true; polybarStyle = "modular"; };
      scaling = { internalResolution = null; standaloneScaleFactor = 1.0; };
      # keyboard.xmodmap = ''
      #   clear lock
      #   clear control
      #   keycode 66 = Control_L
      #   add control = Control_L Control_R
      # '';
    };
  };
}
