# Machine Configuration
# Serial: @SERIAL@
# Generated by Hydrix installer on @DATE@
#
# Config file is named by hardware serial for automatic reinstall detection.
# The visual hostname is always "hydrix".
#
# See machines/example-serial.nix for all available options with documentation.
#
# BOOT MODES:
#   DEFAULT (Lockdown):  No host internet, minimal packages, hardened
#   Administrative:      Full functionality, router VM, all packages
#   Fallback:            Emergency direct WiFi, no VMs
#
# Switch modes (rebuild script auto-detects this machine by serial):
#   rebuild                    -> Lockdown
#   rebuild administrative     -> Admin
#   rebuild fallback           -> Fallback

{ config, lib, pkgs, hydrix, ... }:

{
  imports = [
    ./@SERIAL@-hardware.nix
    ../specialisations/lockdown.nix
    ./grub-entries.nix
    ../shared/usb-blocking.nix
  ];

  # =========================================================================
  # SPECIALISATIONS (Boot Modes)
  # =========================================================================
  # The Hydrix framework defines the infrastructure for each mode:
  #   - Base config = LOCKDOWN (no host internet, builder VM for builds)
  #   - Administrative = adds gateway, libvirtd, full packages
  #   - Fallback = emergency direct WiFi (requires reboot)
  
  specialisation.administrative.configuration = {
    imports = [ ../specialisations/administrative.nix ];
  };

  specialisation.fallback.configuration = {
    imports = [ ../specialisations/fallback.nix ];
  };

  # Custom modes: uncomment to add your own specialisation
  # specialisation.leisure.configuration = {
  #   imports = [ ../specialisations/leisure.nix ];
  # };
  
  users.users.@USERNAME@.hashedPassword = "@PASSWORD_HASH@";

  # =========================================================================
  # HYDRIX CONFIGURATION
  # =========================================================================
  hydrix = {
    # ─────────────────────────────────────────────────────────────────────
    # IDENTITY
    # ─────────────────────────────────────────────────────────────────────
    username = "@USERNAME@";
    hostname = "hydrix";         # Visual hostname (config file identified by serial)
    colorscheme = "@COLORSCHEME@";
    graphical.wallpaper = "${hydrix}/wallpapers/WindowRain.png";

    # Window manager selection - all are off by default; enable exactly one here.
    # i3.enable also gates the X11/xpra stack in all VMs (waypipe used otherwise).
    hyprland.enable = true;   # Wayland/Hyprland stack - start with: hyprland-session
    # sway.enable = true;     # Wayland/Sway stack     - start with: sway-session
    # i3.enable = true;       # X11/i3 stack           - start with: startx

    # ── VM focus border colors ────────────────────────────────────────────
    # Controls how the active window border color changes when you switch to a VM workspace.
    # Default (set by the hyprland module): "dynamic" — maps each VM type to a wal palette color.
    # Override here to lock to the static per-VM colorscheme instead:
    # vmThemeSync.focusDaemon.mode = "static";  # options: "dynamic" (default) | "static"

    disko = {
      enable = true;
      device = "@DEVICE@";
      swapSize = "@SWAP_SIZE@";
      layout = "@LAYOUT@";
      nixosPartition = "@NIXOS_PARTITION@";
      efiPartition = "@EFI_PARTITION@";
      efiBootloaderId = "@EFI_BOOTLOADER_ID@";
    };

    # ─────────────────────────────────────────────────────────────────────
    # ROUTER
    # ─────────────────────────────────────────────────────────────────────
    # WiFi credentials are in shared/wifi.nix (shared across all machines).
    router = {
      type = "@ROUTER_TYPE@";
      wan.mode = "@WAN_MODE@";
      wan.device = if "@WAN_DEVICE@" != "" then "@WAN_DEVICE@" else null;
    };

      # ─── Mullvad VPN (optional) ────────────────────────────────────────
      # 1. mullvad.net →  Account →  WireGuard config →  select server →  download .conf
      # 2. Place downloaded files in ~/hydrix-config/vpn/
      # 3. Copy vpn/mullvad.nix.example → vpn/mullvad.nix, map bridges to files
      # 4. Uncomment the line below and rebuild the router
      #
      # vpn.mullvad = import ../vpn/mullvad.nix;

    # ─────────────────────────────────────────────────────────────────────
    # HARDWARE
    # ─────────────────────────────────────────────────────────────────────
    hardware = {
      platform = "@PLATFORM@";
      isAsus = @IS_ASUS@;
      vfio = {
        enable = @VFIO_ENABLE@;
        pciIds = [ "@WIFI_PCI_ID@" ];
        wifiPciAddress = "@WIFI_PCI_ADDRESS@";
      };
      
      # bluetooth.enable = true;     # DEFAULT: true - Bluetooth + Blueman
      # i2c.enable = true;           # DEFAULT: true - DDC/CI monitor control
      # touchpad.enable = true;      # DEFAULT: true - libinput touchpad
      
      grub.gfxmodeEfi = "@GRUB_GFXMODE@";
    };

    vmMetrics = {
      # vmCollectInterval =  5;  # How often VMs collect metrics (seconds)
      # hostPollInterval  =  5;  # How often host polls VMs (seconds)
      # staleThreshold    = 15;  # Mark VM offline after this many seconds without data
    };

    power = {
      # autoCpuFreq = false;  # HWP (balance_power EPP) handles scaling - no polling daemon needed
    };

    # ─────────────────────────────────────────────────────────────────────
    # SERVICES
    # ─────────────────────────────────────────────────────────────────────
    # services = {
    #   tailscale.enable = true;   # DEFAULT: false - Tailscale VPN mesh
    # };

    # ─────────────────────────────────────────────────────────────────────
    # SECRETS (optional - for GitHub SSH keys, etc.)
    # ─────────────────────────────────────────────────────────────────────
    # Setup workflow:
    #   1. Rebuild once (generates /etc/ssh/ssh_host_ed25519_key)
    #   2. Run: sops-age-pubkey          (prints your age public key)
    #   3. Add key to secrets/.sops.yaml in your hydrix-config
    #   4. Fill secrets/github.yaml, encrypt: cd secrets && sops -e -i github.yaml
    #   5. Set enable = true + github.enable = true, then rebuild
    secrets = {
      enable = false;
      github.enable = false;
      # githubSecretsFile = ../secrets/github.yaml;
    };

  
    # ─────────────────────────────────────────────────────────────────────
    # MICROVM HOST
    # ─────────────────────────────────────────────────────────────────────
    microvmHost = {
      enable = true;
      vms = {
        "microvm-router"   = { autostart = true; };
        # hostsync requires ~/vm-inbox on the host (created automatically when enabled).
        # Disabled by default - enable when you need secure inter-VM file transfers.
        "microvm-hostsync" = { enable = false; };
        # vault requires setup before first use - see DOCUMENTATION.md §Vault VM.
        # Disabled by default - enable and set autostart = true after initializing ~/vault/.
        "microvm-vault"    = { enable = false; };
        # Uncomment VMs that should receive GitHub SSH key from secrets/github.yaml:
        # "microvm-browsing" = { secrets = [ "github" ]; };
        # "microvm-dev"      = { secrets = [ "github" ]; };
        # "microvm-pentest"  = { secrets = [ "github" ]; };
        # "microvm-builder"  = { secrets = [ "github" ]; };
        # "microvm-gitsync"  = { secrets = [ "github" ]; };
      };
    };

    # ─────────────────────────────────────────────────────────────────────
    # BUILDER (lockdown mode nix builds via microvm-builder)
    # ─────────────────────────────────────────────────────────────────────
    builder.enable = true;

    # ─────────────────────────────────────────────────────────────────────
    # GIT-SYNC (lockdown mode git push/pull via microvm-gitsync)
    # ─────────────────────────────────────────────────────────────────────
    gitsync.enable = true;

    # ─────────────────────────────────────────────────────────────────────
    # GRAPHICAL
    # ─────────────────────────────────────────────────────────────────────
    # Shared UI preferences live in shared/graphical.nix (imported for all machines).
    graphical = {
      enable = true;

      # polarity = "dark";  # DEFAULT: "dark"

      # ─── Font ──────────────────────────────────────────────────────────
      # font.family = "Iosevka";
      # font.size   = 10;
      # font.overrides = { alacritty = 10.5; };
      # font.familyOverrides = { alacritty = "Tamzen"; };

      # ─── UI layout ─────────────────────────────────────────────────────
      # ui.gaps        = 15;          # DEFAULT: 15 - window gaps (px)
      # ui.barHeight   = 23;          # DEFAULT: 23
      # ui.border      = 2;           # DEFAULT: 2  - window border width
      # ui.floatingBar = true;        # DEFAULT: true - floating waybar
      # ui.cornerRadius = 2;          # DEFAULT: 2  - corner rounding radius

      # ─── Hyprland display scaling ──────────────────────────────────────
      # scaling.hyprInternalScale  = 1.5;       # UI scale (1.5 -> 1280×800, 1.25 -> 1536×960 logical)
      # scaling.hyprInternalOutput = "eDP-1";   # DEFAULT: "eDP-1" (run: hyprctl monitors)

      # ─── Hyprland keyboard remapping ───────────────────────────────────
      # Custom xkb keymap — takes precedence over layout/variant from shared/common.nix.
      # Use for key remapping (e.g. § -> ~, CapsLock -> Ctrl). See example-serial.nix.
      # keyboard.xkbFile = pkgs.writeText "my-keymap" ''
      #   xkb_keymap {
      #     xkb_keycodes { include "evdev+aliases(qwerty)" };
      #     xkb_types    { include "complete" };
      #     xkb_compat   { include "complete" };
      #     xkb_symbols  {
      #       include "pc+se+inet(evdev)"
      #       key <CAPS> { [ Control_L, Control_L ] };
      #     };
      #     xkb_geometry { include "pc(pc105)" };
      #   };
      # '';

      # ─── X11/i3 settings ───────────────────────────────────────────────
      # scaling.internalResolution = "1920x1200";  # i3/xrandr standalone display mode
      # ui.polybarStyle = "modular";               # "unibar", "modular", "pills"
      # keyboard.xmodmap = ''
      #   clear lock
      #   clear control
      #   keycode 66 = Control_L
      #   add control = Control_L Control_R
      # '';

      # ─── Sway display scaling ──────────────────────────────────────────
      # scaling.swayInternalScale  = 1.25;
      # scaling.swayInternalOutput = "eDP-1";   # DEFAULT: "eDP-1"

      # ─── Lockscreen ────────────────────────────────────────────────────
      # lockscreen.idleTimeout = 600;   # DEFAULT: 600 seconds
      # lockscreen.text      = "Locked";
      # lockscreen.wrongText = "Wrong password";

      # ─── Blue light filter ─────────────────────────────────────────────
      # bluelight.enable      = true;   # DEFAULT: true
      # bluelight.defaultTemp = 4500;   # DEFAULT: 4500K
    };
  };

  # SSH is disabled globally by default - uncomment to enable on this machine
  # services.openssh.enable = true;

  # Uncomment to enable libvirt/QEMU/virt-manager (pentest VMs, Windows VMs, etc.)
  # hydrix.libvirt.enable = true;
  # hydrix.libvirt.grabKey = "65507,65513";  # Left Ctrl+Alt — find keysyms with `xev`
}
