# Dunst Notification Daemon Configuration
#
# Dynamic wal colors support — dunstrc is generated at runtime by the
# generate-dunstrc script from scaling.json and the wal cache.
# Notifications appear top-right, below the bar (bar reserves its space),
# inset by gaps + 5px on both axes.
#
# This module:
# - Disables home-manager's dunst service (we manage it ourselves)
# - Provides a dunstrc generation script with all settings + wal colors
# - Creates a systemd user service that generates config then runs dunst
{
  config,
  lib,
  pkgs,
  ...
}: let
  username = config.hydrix.username;
  cfg = config.hydrix.graphical;

  fontName = cfg.font.family;
  fontSize = cfg.font.size;

  generateDunstrc = pkgs.writeShellScript "generate-dunstrc" ''
    #!/usr/bin/env bash
    # Generate dunstrc with wal colors and dynamic sizing from scaling.json

    SCALING_JSON="$HOME/.config/hydrix/scaling.json"
    SCALING_JSON_VM="/mnt/hydrix-config/scaling.json"
    DUNST_DIR="$HOME/.config/dunst"
    DUNSTRC="$DUNST_DIR/dunstrc"

    ${pkgs.coreutils}/bin/mkdir -p "$DUNST_DIR"

    # Read scaling values from scaling.json (or use defaults)
    if [ -f "$SCALING_JSON" ]; then
      SCALE_FILE="$SCALING_JSON"
    elif [ -f "$SCALING_JSON_VM" ]; then
      SCALE_FILE="$SCALING_JSON_VM"
    else
      SCALE_FILE=""
    fi

    if [ -n "$SCALE_FILE" ]; then
      GAPS=$(${pkgs.jq}/bin/jq -r '.sizes.gaps // ${toString cfg.ui.gaps}' "$SCALE_FILE")
      BAR_HEIGHT=$(${pkgs.jq}/bin/jq -r '.sizes.bar_height // ${toString cfg.ui.barHeight}' "$SCALE_FILE")
      BORDER=$(${pkgs.jq}/bin/jq -r '.sizes.border // ${toString cfg.ui.border}' "$SCALE_FILE")
      CORNER_RADIUS=$(${pkgs.jq}/bin/jq -r '.sizes.corner_radius // ${toString cfg.ui.cornerRadius}' "$SCALE_FILE")
      FONT_NAME=$(${pkgs.jq}/bin/jq -r '.font_names.dunst // .font_name // "${fontName}"' "$SCALE_FILE")
      FONT_SIZE=$(${pkgs.jq}/bin/jq -r '.fonts.dunst // ${toString fontSize}' "$SCALE_FILE")
      OVERLAY_ALPHA=$(${pkgs.jq}/bin/jq -r '.sizes.overlay_alpha_hex // "D9"' "$SCALE_FILE")
      DUNST_WIDTH=${toString cfg.ui.dunstWidth}
    else
      GAPS=${toString cfg.ui.gaps}
      BAR_HEIGHT=${toString cfg.ui.barHeight}
      BORDER=${toString cfg.ui.border}
      CORNER_RADIUS=${toString cfg.ui.cornerRadius}
      FONT_NAME="${fontName}"
      FONT_SIZE=${toString fontSize}
      OVERLAY_ALPHA="D9"
      DUNST_WIDTH=${toString cfg.ui.dunstWidth}
    fi

    # Padding scaled from bar height
    PADDING=$((BAR_HEIGHT / 4))
    [ "$PADDING" -lt 4 ] && PADDING=4
    [ "$PADDING" -gt 8 ] && PADDING=8
    H_PADDING=$((PADDING + 4))

    # Pill radius: matches waybar island pills (cornerRadius * pillRadiusScale)
    PILL_RADIUS=$((CORNER_RADIUS * ${toString (builtins.floor cfg.ui.pillRadiusScale)}))

    # Offset: gaps + 5px on both axes; bar reserves its own space via exclusive zone
    OFFSET=$((GAPS + 5))

    # Extract colors from wal cache (host and VMs)
    WAL_COLORS="$HOME/.cache/wal/colors.json"
    if [ -f "$WAL_COLORS" ]; then
      BG_RAW=$(${pkgs.jq}/bin/jq -r '.special.background // .colors.color0' "$WAL_COLORS")
      FG=$(${pkgs.jq}/bin/jq -r '.special.foreground // .colors.color7' "$WAL_COLORS")
      PREFIX=$(${pkgs.jq}/bin/jq -r '.colors.color3' "$WAL_COLORS")
      FRAME=$(${pkgs.jq}/bin/jq -r '.colors.color5' "$WAL_COLORS")
      FRAME_LOW=$(${pkgs.jq}/bin/jq -r '.colors.color2' "$WAL_COLORS")
      FRAME_CRIT=$(${pkgs.jq}/bin/jq -r '.colors.color1' "$WAL_COLORS")
    else
      BG_RAW="#101116"
      FG="#c0caf5"
      PREFIX="#e0af68"
      FRAME="#bb9af7"
      FRAME_LOW="#98971a"
      FRAME_CRIT="#cc241d"
    fi
    BG_LOW_RAW="$BG_RAW"
    BG="''${BG_RAW}''${OVERLAY_ALPHA}"
    BG_LOW="''${BG_LOW_RAW}''${OVERLAY_ALPHA}"

    # Generate the full dunstrc
    ${pkgs.coreutils}/bin/cat > "$DUNSTRC" << DUNSTRC_EOF
# Generated by Hydrix - DO NOT EDIT
# Regenerated when colors change (walrgb, randomwalrgb, etc.)

[global]
font = $FONT_NAME $FONT_SIZE

monitor = ${
      if cfg.ui.dunstEnablePopup
      then "0"
      else "-1"
    }
follow = mouse

width = $DUNST_WIDTH
height = 300
origin = top-right
offset = ''${OFFSET}x''${OFFSET}
scale = 0

progress_bar = true
progress_bar_height = 10
progress_bar_frame_width = 1
progress_bar_min_width = 150
progress_bar_max_width = 300

notification_limit = 5
indicate_hidden = true
transparency = 0
separator_height = 0
padding = $PADDING
horizontal_padding = $H_PADDING
text_icon_padding = 0
frame_width = $BORDER
gap_size = 0
separator_color = frame
sort = true

line_height = 0
markup = full
format = "<b><span foreground='$PREFIX'>%s</span></b>\n<span foreground='$FG'>%b</span>"
alignment = left
vertical_alignment = center
show_age_threshold = 60
ellipsize = middle
word_wrap = yes
ignore_newline = false
stack_duplicates = true
hide_duplicate_count = false
show_indicators = true

enable_recursive_icon_lookup = true
icon_position = left
min_icon_size = 32
max_icon_size = 64

sticky_history = true
history_length = 20

browser = ${cfg.ui.dunstBrowser}
always_run_script = true
title = Dunst
class = Dunst
corner_radius = $PILL_RADIUS
ignore_dbusclose = false
sound = ${
      if cfg.ui.dunstSound != null && cfg.ui.dunstSound != ""
      then "true"
      else "false"
    }
sound_command = ${
      if cfg.ui.dunstSound != null && cfg.ui.dunstSound != ""
      then "canberra-gtk-play -f ${cfg.ui.dunstSound}"
      else ""
    }

mouse_left_click = close_current
mouse_middle_click = do_action, close_current
mouse_right_click = close_all

[urgency_low]
background = "$BG_LOW"
foreground = "$FG"
frame_color = "$FRAME_LOW"
timeout = ${toString cfg.ui.dunstUrgencyTimeout.low}

[urgency_normal]
background = "$BG"
foreground = "$FG"
frame_color = "$FRAME"
timeout = ${toString cfg.ui.dunstUrgencyTimeout.normal}

[urgency_critical]
background = "$BG"
foreground = "$FG"
frame_color = "$FRAME_CRIT"
timeout = ${toString cfg.ui.dunstUrgencyTimeout.critical}
DUNSTRC_EOF
  '';
in {
  config = lib.mkIf cfg.enable {
    environment.systemPackages = [
      pkgs.dunst
      pkgs.libnotify
      (pkgs.runCommand "generate-dunstrc" {} ''
        mkdir -p $out/bin
        cp ${generateDunstrc} $out/bin/generate-dunstrc
        chmod +x $out/bin/generate-dunstrc
      '')
    ];

    home-manager.users.${username} = {pkgs, ...}: {
      services.dunst.enable = false;

      systemd.user.services.dunst = {
        Unit = {
          Description = "Dunst notification daemon (Hydrix)";
          Documentation = "man:dunst(1)";
          PartOf = ["graphical-session.target"];
          After = ["graphical-session-pre.target" "init-wal-cache.service"];
        };
        Service = {
          Type = "dbus";
          BusName = "org.freedesktop.Notifications";
          ExecStartPre = "${generateDunstrc}";
          ExecStart = "${pkgs.dunst}/bin/dunst";
          Restart = "on-failure";
          RestartSec = 1;
          ExecReload = "${pkgs.coreutils}/bin/kill -HUP $MAINPID";
        };
        Install = {
          WantedBy = ["graphical-session.target"];
        };
      };
    };
  };
}
