# Obsidian Note-Taking App Configuration
#
# Home Manager module for Obsidian.
# Configures appearance and CSS snippets for font/color theming.
#
# CSS snippet is deployed to each vault in hydrix.graphical.obsidian.vaultPaths.
# Appearance.json is patched (not replaced) via activation script so that
# in-app settings changes are preserved where possible.

{ config, lib, pkgs, ... }:

let
  username = config.hydrix.username;

  # Get font configuration from unified options
  fontCfg = config.hydrix.graphical.font;
  fontName = fontCfg.family;
  # Use override if set, otherwise scale base size
  fontSize = fontCfg.overrides.obsidian or fontCfg.size;
  headerFontSize = fontCfg.overrides.obsidianHeader or (builtins.floor (fontCfg.size * 1.5));

  # Base16 colors from Stylix
  colors = config.lib.stylix.colors.withHashtag;
  polarity = config.hydrix.graphical.polarity;

  # Vault paths to deploy to
  vaultPaths = config.hydrix.graphical.obsidian.vaultPaths;

  # Generate the CSS snippet with fonts AND colors
  snippetCss = ''
    /* Hydrix Obsidian Theme - Auto-generated by Home Manager */
    /* Font: ${fontName} | Colorscheme: ${config.hydrix.colorscheme} */

    .theme-${polarity} {
      /* Base16 colorscheme — smooth ramp from darkest (00) to lightest text (100) */
      --color-base-00: ${colors.base00};
      --color-base-05: ${colors.base01};
      --color-base-10: ${colors.base01};
      --color-base-20: ${colors.base02};
      --color-base-25: ${colors.base02};
      --color-base-30: ${colors.base03};
      --color-base-35: ${colors.base03};
      --color-base-40: ${colors.base04};
      --color-base-50: ${colors.base04};
      --color-base-60: ${colors.base05};
      --color-base-70: ${colors.base05};
      --color-base-100: ${colors.base05};

      --color-accent: ${colors.base0D};
      --color-accent-1: ${colors.base0E};

      /* Syntax highlighting */
      --color-red: ${colors.base08};
      --color-orange: ${colors.base09};
      --color-yellow: ${colors.base0A};
      --color-green: ${colors.base0B};
      --color-cyan: ${colors.base0C};
      --color-blue: ${colors.base0D};
      --color-purple: ${colors.base0E};

      /* UI elements — backgrounds stay near base00, text always base05 */
      --background-primary: ${colors.base00};
      --background-primary-alt: ${colors.base01};
      --background-secondary: ${colors.base01};
      --background-secondary-alt: ${colors.base00};
      --background-modifier-border: ${colors.base02};
      --background-modifier-form-field: ${colors.base01};
      --background-modifier-form-field-highlighted: ${colors.base02};
      --background-modifier-success: ${colors.base0B};
      --background-modifier-error: ${colors.base08};
      --background-modifier-error-hover: ${colors.base08};
      --background-modifier-cover: rgba(0, 0, 0, 0.8);

      /* All text uses base05 or higher to avoid matching base01-base03 backgrounds */
      --text-normal: ${colors.base05};
      --text-muted: ${colors.base05};
      --text-faint: ${colors.base05};
      --text-error: ${colors.base08};
      --text-accent: ${colors.base0D};
      --text-accent-hover: ${colors.base0C};
      --text-on-accent: ${colors.base00};
      --text-selection: ${colors.base02};

      --interactive-normal: ${colors.base01};
      --interactive-hover: ${colors.base02};
      --interactive-accent: ${colors.base0D};
      --interactive-accent-hover: ${colors.base0C};

      /* Title bar */
      --titlebar-background: ${colors.base00};
      --titlebar-background-focused: ${colors.base01};
      --titlebar-text-color: ${colors.base05};
    }

    * :not([class*="icon"]):not([class*="fa-"]):not([class*="material"]):not([class*="glyph"]):not(i):not(h1):not(h2):not(h3):not(.el-h1):not(.el-h2):not(.el-h3):not(.mod-header):not(.el-ul):not(code):not(.el-text) {
      font-family: "${fontName}", monospace !important;
      font-size: ${toString fontSize}px !important;
      -webkit-font-smoothing: none !important;
      -moz-osx-font-smoothing: unset !important;
      font-smooth: never !important;
      text-rendering: optimizeSpeed !important;
    }

    h1, h2, h3,
    div.el-h1,
    div.el-h2,
    div.el-h3,
    div.mod-header.mod-ui {
      font-family: "${fontName}", monospace !important;
      font-size: ${toString headerFontSize}px !important;
      -webkit-font-smoothing: none !important;
      -moz-osx-font-smoothing: unset !important;
      font-smooth: never !important;
      text-rendering: optimizeSpeed !important;
    }

    .el-ul,
    code,
    .el-text {
      font-family: "${fontName}", monospace !important;
      font-size: ${toString fontSize}px !important;
      -webkit-font-smoothing: none !important;
      -moz-osx-font-smoothing: unset !important;
      font-smooth: never !important;
      text-rendering: optimizeSpeed !important;
    }

    .menu .menu-item,
    .suggestion-item,
    .prompt-instruction {
      font-size: ${toString fontSize}px !important;
      -webkit-font-smoothing: none !important;
      -moz-osx-font-smoothing: unset !important;
      font-smooth: never !important;
      text-rendering: optimizeSpeed !important;
    }

    :root {
      --font-text-size: ${toString fontSize}px !important;
      --editor-font-size: ${toString fontSize}px !important;
      --font-ui-large: ${toString headerFontSize}px !important;
      --default-font: "${fontName}" !important;
      --font-interface: "${fontName}" !important;
      --font-text: "${fontName}" !important;
    }
  '';

  # Appearance.json — no cssTheme override, enables our snippet
  appearanceJson = builtins.toJSON {
    theme = "obsidian";
    baseFontSize = fontSize;
    baseFontSizeAction = true;
    nativeMenus = false;
    enabledCssSnippets = [ "hydrix-theme" ];
    interfaceFontFamily = fontName;
    textFontFamily = fontName;
    monospaceFontFamily = fontName;
  };

  # On hosts, Obsidian is only included when hostEnable is true.
  # VMs always get Obsidian when graphical is enabled.
  isHost = config.hydrix.vmType == "host" || config.hydrix.vmType == null;
  obsidianEnabled = config.hydrix.graphical.enable
    && (!isHost || config.hydrix.graphical.obsidian.hostEnable);

  # Build home.file entries for each vault
  vaultSnippetFiles = builtins.listToAttrs (map (vault: {
    name = "${vault}/.obsidian/snippets/hydrix-theme.css";
    value = { text = snippetCss; };
  }) vaultPaths);

in {
  config = lib.mkIf obsidianEnabled {
    # Install Obsidian
    environment.systemPackages = [ pkgs.obsidian ];

    home-manager.users.${username} = { pkgs, lib, ... }: {
      # Deploy CSS snippet to global config dir and each vault
      home.file = {
        ".config/obsidian/snippets/hydrix-theme.css".text = snippetCss;
      } // vaultSnippetFiles;

      # Patch vault appearance.json files via activation script
      # This preserves user changes while ensuring our snippet is enabled
      # and no conflicting cssTheme is set
      home.activation.obsidianAppearance = lib.mkIf (vaultPaths != []) (
        lib.hm.dag.entryAfter [ "writeBoundary" ] ''
          ${lib.concatMapStringsSep "\n" (vault: ''
            VAULT_DIR="$HOME/${vault}/.obsidian"
            APPEARANCE="$VAULT_DIR/appearance.json"
            if [ -d "$VAULT_DIR" ]; then
              mkdir -p "$VAULT_DIR/snippets"
              if [ -f "$APPEARANCE" ]; then
                # Patch existing: remove cssTheme, ensure hydrix-theme snippet enabled
                ${pkgs.jq}/bin/jq '
                  del(.cssTheme) |
                  .enabledCssSnippets = (
                    (.enabledCssSnippets // [])
                    | if any(. == "hydrix-theme") then . else . + ["hydrix-theme"] end
                  ) |
                  .interfaceFontFamily = "${fontName}" |
                  .textFontFamily = "${fontName}" |
                  .monospaceFontFamily = "${fontName}"
                ' "$APPEARANCE" > "$APPEARANCE.tmp" && mv "$APPEARANCE.tmp" "$APPEARANCE"
              else
                echo '${appearanceJson}' > "$APPEARANCE"
              fi
            fi
          '') vaultPaths}
        ''
      );
    };
  };
}
