# Zathura PDF Viewer Configuration
#
# Home Manager module for Zathura.
# Colors come from pywal at runtime via ~/.config/zathura/zathurarc-wal,
# generated by refresh-colors / walrgb. Stylix theming is disabled to
# prevent its build-time colors from overriding the runtime wal colors.

{ config, lib, pkgs, ... }:

let
  username = config.hydrix.username;

  # Scaling values
  sc = config.hydrix.graphical.scaling.computed;
in {
  config = lib.mkIf config.hydrix.graphical.enable {
    home-manager.users.${username} = { pkgs, ... }: {
      # Stylix sets colors via programs.zathura.options which are written after
      # extraConfig in the generated file, overriding the wal include. Disable it
      # so wal owns zathura colors entirely.
      stylix.targets.zathura.enable = lib.mkForce false;

      programs.zathura = {
        enable = true;

        # Load wal colors generated by refresh-colors/walrgb at runtime.
        # On a fresh install, init-wal-cache generates this file from the
        # configured colorscheme before the user runs walrgb.
        extraConfig = "include ~/.config/zathura/zathurarc-wal";

        options = {
          # Colors managed via zathurarc-wal (see extraConfig above)

          # Document recoloring behavior
          recolor = true;
          recolor-reverse-video = true;
          recolor-keephue = false;

          # UI Settings (scaled)
          statusbar-h-padding = sc.padding;
          statusbar-v-padding = sc.padding;
          page-padding = sc.border;
          selection-clipboard = "clipboard";

          # Behavior
          scroll-page-aware = true;
          scroll-full-overlap = 0.01;
          scroll-step = 100;
          zoom-min = 10;
          zoom-max = 400;
          zoom-step = 10;

          # Search
          incremental-search = true;

          # Sandbox (disable for better compatibility)
          sandbox = "none";
        };

        mappings = {
          # Vim-like navigation
          D = "toggle_page_mode";
          r = "reload";
          R = "rotate";
          K = "zoom in";
          J = "zoom out";
          i = "recolor";
          p = "print";
        };
      };
    };
  };
}
