# NOTE: PERSONAL SCRIPT - REMOVE BEFORE PUBLIC RELEASE
# This is a personal script for syncing colors to borttappat.github.io
#
# GitHub Pages Color Export Module
#
# Exports pywal colors to the GitHub Pages site at ~/borttappat.github.io
# Generates CSS variables for the CRT-styled personal site.
#
# COMMANDS
# --------
#   export-github-colors    Export current wal colors to GitHub site CSS
#   export-github-colors -v Verbose mode (show generated CSS)
#
# INTEGRATION
# -----------
# This module can be called from walrgb/randomwalrgb or refresh-colors
# to automatically sync colors to the GitHub site.

{ config, lib, pkgs, ... }:

let
  cfg = config.hydrix.graphical;
  username = config.hydrix.username;
  vmType = config.hydrix.vmType;
  isVM = vmType != null && vmType != "host";
  jq = "${pkgs.jq}/bin/jq";

  # Export wal colors to GitHub Pages CSS
  exportGithubColorsScript = pkgs.writeShellScriptBin "export-github-colors" ''
    #!/usr/bin/env bash
    # Export pywal colors to GitHub Pages site CSS
    #
    # Usage: export-github-colors [-v|--verbose]

    set -euo pipefail

    # Configuration
    SITE_COLORS="''${SITE_COLORS:-$HOME/borttappat.github.io/assets/css/colors.css}"
    WAL_COLORS_CSS="''${WAL_COLORS_CSS:-$HOME/.cache/wal/colors.css}"
    WAL_COLORS_JSON="$HOME/.cache/wal/colors.json"
    VERBOSE=false

    # Parse arguments
    while [[ $# -gt 0 ]]; do
      case $1 in
        -v|--verbose)
          VERBOSE=true
          shift
          ;;
        *)
          echo "Usage: export-github-colors [-v|--verbose]"
          exit 1
          ;;
      esac
    done

    # Check if wal colors exist
    if [[ ! -f "$WAL_COLORS_CSS" ]]; then
      echo "Error: wal colors not found at $WAL_COLORS_CSS"
      echo "Run 'walrgb <image>' or 'apply-colorscheme <scheme.json>' first"
      exit 1
    fi

    # Check if site directory exists
    SITE_DIR="$(dirname "$SITE_COLORS")"
    if [[ ! -d "$(dirname "$SITE_DIR")" ]]; then
      echo "Warning: GitHub site directory not found at ~/borttappat.github.io"
      echo "Creating directory structure..."
    fi
    mkdir -p "$SITE_DIR"

    # Extract flicker color from wal (use color1 with low alpha for CRT effect)
    FLICKER_COLOR="rgba(152, 217, 2, 0.01)"
    if [[ -f "$WAL_COLORS_JSON" ]]; then
      # Try to get a green-ish color from the palette for flicker
      COLOR6=$(${jq} -r '.colors.color6 // "#98d902"' "$WAL_COLORS_JSON")
      # Convert hex to rgba with low alpha
      if [[ "$COLOR6" =~ ^#([0-9A-Fa-f]{2})([0-9A-Fa-f]{2})([0-9A-Fa-f]{2})$ ]]; then
        R=$((16#''${BASH_REMATCH[1]}))
        G=$((16#''${BASH_REMATCH[2]}))
        B=$((16#''${BASH_REMATCH[3]}))
        FLICKER_COLOR="rgba($R, $G, $B, 0.01)"
      fi
    fi

    # Generate the CSS file
    # Lines 12-28 of wal's colors.css contain the --colorN variable definitions
    {
      echo "/* Theme colors - automatically generated by export-github-colors */"
      echo "/* Source: pywal colors from ~/.cache/wal/colors.css */"
      echo ":root {"
      echo "    /* Colors extracted from pywal */"
      sed -n '12,28p' "$WAL_COLORS_CSS"
      echo ""
      echo "    /* Additional theme variables for CRT effects */"
      echo "    --scanline-color: rgba(12, 12, 12, 0.1);"
      echo "    --flicker-color: $FLICKER_COLOR;"
      echo "    --text-shadow-color: var(--color1);"
      echo "    --header-shadow-color: var(--color0);"
      echo "}"
    } > "$SITE_COLORS"

    echo "Exported wal colors to: $SITE_COLORS"

    # Verbose output
    if [[ "$VERBOSE" == "true" ]]; then
      echo ""
      echo "Generated CSS:"
      echo "=============="
      cat "$SITE_COLORS"
    fi
  '';

in {
  config = lib.mkIf (cfg.enable && !isVM) {
    # Only install on host (not in VMs - they don't need GitHub site access)
    environment.systemPackages = [
      exportGithubColorsScript
    ];

    # Also add to user packages via home-manager
    home-manager.users.${username} = { ... }: {
      home.packages = [
        exportGithubColorsScript
      ];
    };
  };
}
