# Machine Configuration Template
#
# This is generated by install-hydrix.sh with your machine's settings.
#
# Variables in {{BRACKETS}} are replaced by the installer.
{ config, lib, pkgs, ... }:

{
  # =========================================================================
  # DISKO (disk partitioning) - set by installer
  # =========================================================================
  imports = [
    # Disko template - options: full-disk-plain, full-disk-luks, dual-boot-luks
    (import ../disko/full-disk-plain.nix {
      device = "/dev/nvme0n1";  # {{DISK_DEVICE}}
      swapSize = "16G";         # {{SWAP_SIZE}}
    })
  ];

  # =========================================================================
  # HYDRIX OPTIONS
  # =========================================================================
  hydrix = {
    # Identity
    username = "user";          # {{USERNAME}}
    hostname = "hydrix";        # {{HOSTNAME}}
    vmType = "host";
    colorscheme = "puccy";

    # Router
    router = {
      type = "microvm";
      autostart = false;  # Set true after testing
      username = "user";  # {{USERNAME}}
      hashedPassword = null;  # {{ROUTER_HASH}} - set with: mkpasswd -m sha-512

      wifi = {
        ssid = "";      # {{WIFI_SSID}}
        password = "";  # {{WIFI_PASSWORD}}
      };
    };

    # Hardware (auto-detected by installer)
    hardware = {
      platform = "intel";   # {{CPU_PLATFORM}} - intel, amd, or generic
      isAsus = false;       # {{IS_ASUS}}

      vfio = {
        enable = true;
        pciIds = [ "8086:a840" ];     # {{VFIO_IDS}} - WiFi card vendor:device
        wifiPciAddress = "00:14.3";   # {{WIFI_PCI}} - from: lspci -D | grep -i wireless
      };

      grub.gfxmodeEfi = "1920x1200";  # {{GRUB_GFX}}
    };

    # Secrets
    secrets = {
      enable = false;
      github.enable = false;
    };

    # MicroVM Host
    microvmHost = {
      enable = true;
      vms = {
        "microvm-router".enable = true;
        "microvm-browsing".enable = false;
        "microvm-pentest".enable = false;
      };
    };

    # Graphical
    graphical = {
      enable = true;
      font.size = 10;
      ui = {
        gaps = 10;
        floatingBar = true;
        polybarStyle = "modular";
      };
      scaling = {
        internalResolution = null;
        standaloneScaleFactor = 1.0;
      };
    };
  };

  # =========================================================================
  # LOCALE — set as native NixOS options
  # =========================================================================
  time.timeZone = "Europe/Stockholm";           # {{TIMEZONE}}
  i18n.defaultLocale = "en_US.UTF-8";           # {{LOCALE}}
  console.keyMap = "sv-latin1";                  # {{CONSOLE_KEYMAP}}
  services.xserver.xkb.layout = "se";           # {{XKB_LAYOUT}}
  services.xserver.xkb.variant = "";            # {{XKB_VARIANT}}
}
