#!/run/current-system/sw/bin/bash
# Rofi launcher with dynamic scaling from scaling.json

SCALING_JSON="$HOME/.config/hydrix/scaling.json"
DYNAMIC_CONFIG="$HOME/.config/hydrix/dynamic/rofi.rasi"

# Check for dynamic config first (generated by hydrix-scale)
if [ -f "$DYNAMIC_CONFIG" ]; then
    exec rofi "$@" -config "$DYNAMIC_CONFIG"
fi

# Fallback: read from scaling.json and use with default config
if [ -f "$SCALING_JSON" ]; then
    ROFI_FONT_SIZE=$(jq -r '.fonts.rofi // 12' "$SCALING_JSON")
    FONT_NAME=$(jq -r '.font_name // "Iosevka"' "$SCALING_JSON")
    exec rofi "$@" -font "$FONT_NAME $ROFI_FONT_SIZE"
fi

# Ultimate fallback
exec rofi "$@"
