# Generates a static pywal cache for VMs based on VM type
# This ensures VMs have consistent colors while using the same templates as the host

set -euo pipefail

VM_TYPE="${1:-}"

if [ -z "$VM_TYPE" ]; then
    echo "Usage: vm-static-colors.sh <pentest|comms|browsing|dev|host>"
    exit 1
fi

echo "Generating static color scheme for VM type: $VM_TYPE"

# Color scheme definitions
# Each VM/host type gets a distinctive accent color
case "$VM_TYPE" in
    pentest)
        ACCENT_HEX="ea6c73"  # Red - aggressive, warning, security focus
        WALLPAPER_NAME="pentest-red.jpg"
        ;;
    comms)
        ACCENT_HEX="6c89ea"  # Blue - calm, communication, connectivity
        WALLPAPER_NAME="comms-blue.jpg"
        ;;
    browsing)
        ACCENT_HEX="73ea6c"  # Green - safe, browsing, general use
        WALLPAPER_NAME="browsing-green.jpg"
        ;;
    dev)
        ACCENT_HEX="ba6cea"  # Purple - creative, development, building
        WALLPAPER_NAME="dev-purple.jpg"
        ;;
    host)
        ACCENT_HEX="7aa2f7"  # Neutral blue - default host theme
        WALLPAPER_NAME="host-default.jpg"
        ;;
    *)
        echo "Unknown VM type: $VM_TYPE"
        echo "Valid types: pentest, comms, browsing, dev, host"
        exit 1
        ;;
esac

# Ensure cache directory exists
mkdir -p ~/.cache/wal

# Generate 16-color palette from accent color
# We'll create a simple palette by varying brightness/saturation
cat > ~/.cache/wal/colors << EOF
#1a1b26
#${ACCENT_HEX}
#a9b1d6
#7aa2f7
#bb9af7
#73daca
#${ACCENT_HEX}
#c0caf5
#414868
#${ACCENT_HEX}
#a9b1d6
#7aa2f7
#bb9af7
#73daca
#${ACCENT_HEX}
#c0caf5
EOF

# Generate colors.json for pywal compatibility
cat > ~/.cache/wal/colors.json << EOF
{
    "special": {
        "background": "#1a1b26",
        "foreground": "#c0caf5",
        "cursor": "#${ACCENT_HEX}"
    },
    "colors": {
        "color0": "#1a1b26",
        "color1": "#${ACCENT_HEX}",
        "color2": "#a9b1d6",
        "color3": "#7aa2f7",
        "color4": "#bb9af7",
        "color5": "#73daca",
        "color6": "#${ACCENT_HEX}",
        "color7": "#c0caf5",
        "color8": "#414868",
        "color9": "#${ACCENT_HEX}",
        "color10": "#a9b1d6",
        "color11": "#7aa2f7",
        "color12": "#bb9af7",
        "color13": "#73daca",
        "color14": "#${ACCENT_HEX}",
        "color15": "#c0caf5"
    }
}
EOF

# Generate colors.css for web integrations
cat > ~/.cache/wal/colors.css << EOF
/* Pywal colors - Static ${VM_TYPE} theme */

:root {
    /* Special */
    --background: #1a1b26;
    --foreground: #c0caf5;
    --cursor: #${ACCENT_HEX};

    /* Colors */
    --color0: #1a1b26;
    --color1: #${ACCENT_HEX};
    --color2: #a9b1d6;
    --color3: #7aa2f7;
    --color4: #bb9af7;
    --color5: #73daca;
    --color6: #${ACCENT_HEX};
    --color7: #c0caf5;
    --color8: #414868;
    --color9: #${ACCENT_HEX};
    --color10: #a9b1d6;
    --color11: #7aa2f7;
    --color12: #bb9af7;
    --color13: #73daca;
    --color14: #${ACCENT_HEX};
    --color15: #c0caf5;
}
EOF

# Generate sequences file for terminal color restoration with actual escape chars
{
  printf '\033]4;0;#1a1b26\007'
  printf '\033]4;1;#%s\007' "$ACCENT_HEX"
  printf '\033]4;2;#a9b1d6\007'
  printf '\033]4;3;#7aa2f7\007'
  printf '\033]4;4;#bb9af7\007'
  printf '\033]4;5;#73daca\007'
  printf '\033]4;6;#%s\007' "$ACCENT_HEX"
  printf '\033]4;7;#c0caf5\007'
  printf '\033]4;8;#414868\007'
  printf '\033]4;9;#%s\007' "$ACCENT_HEX"
  printf '\033]4;10;#a9b1d6\007'
  printf '\033]4;11;#7aa2f7\007'
  printf '\033]4;12;#bb9af7\007'
  printf '\033]4;13;#73daca\007'
  printf '\033]4;14;#%s\007' "$ACCENT_HEX"
  printf '\033]4;15;#c0caf5\007'
  printf '\033]10;#c0caf5\007'   # Foreground
  printf '\033]11;#1a1b26\007'   # Background
  printf '\033]12;#%s\007' "$ACCENT_HEX"  # Cursor
  printf '\033]708;#1a1b26\007'  # Border
} > ~/.cache/wal/sequences

# Generate Xresources for terminal cursor colors
cat > ~/.cache/wal/colors.Xresources << EOF
! X colors.
! Generated by vm-static-colors for ${VM_TYPE}
*foreground:        #c0caf5
*background:        #1a1b26
*.foreground:       #c0caf5
*.background:       #1a1b26
URxvt*foreground:   #c0caf5
XTerm*foreground:   #c0caf5
UXTerm*foreground:  #c0caf5
URxvt*background:   [100]#1a1b26
XTerm*background:   #1a1b26
UXTerm*background:  #1a1b26
URxvt*cursorColor:  #${ACCENT_HEX}
XTerm*cursorColor:  #${ACCENT_HEX}
UXTerm*cursorColor: #${ACCENT_HEX}
URxvt*borderColor:  [100]#1a1b26

! Colors 0-15.
*.color0: #1a1b26
*color0:  #1a1b26
*.color1: #${ACCENT_HEX}
*color1:  #${ACCENT_HEX}
*.color2: #a9b1d6
*color2:  #a9b1d6
*.color3: #7aa2f7
*color3:  #7aa2f7
*.color4: #bb9af7
*color4:  #bb9af7
*.color5: #73daca
*color5:  #73daca
*.color6: #${ACCENT_HEX}
*color6:  #${ACCENT_HEX}
*.color7: #c0caf5
*color7:  #c0caf5
*.color8: #414868
*color8:  #414868
*.color9: #${ACCENT_HEX}
*color9:  #${ACCENT_HEX}
*.color10: #a9b1d6
*color10:  #a9b1d6
*.color11: #7aa2f7
*color11:  #7aa2f7
*.color12: #bb9af7
*color12:  #bb9af7
*.color13: #73daca
*color13:  #73daca
*.color14: #${ACCENT_HEX}
*color14:  #${ACCENT_HEX}
*.color15: #c0caf5
*color15:  #c0caf5
EOF

# Mark as generated
touch ~/.cache/wal/.static-colors-generated
echo "VM_TYPE=$VM_TYPE" > ~/.cache/wal/.static-colors-type

echo "Static color scheme generated successfully for $VM_TYPE"
echo "Colors will persist across reboots and remain ${VM_TYPE}-themed"
