#!/usr/bin/env bash
# VPN Assignment Script for Router VM
# Manages which VPN tunnel each network bridge uses via policy routing.
#
# Network map is loaded at runtime from /etc/hydrix-router/network-map
# (generated by Nix from all declared profiles — no hardcoded network names).
#
# Usage:
#   vpn-assign <network> <vpn-name|direct|blocked>
#   vpn-assign browsing mullvad-browsing  # Route browsing VM through Mullvad
#   vpn-assign pentest mullvad-pentest    # Route pentest VM through Mullvad
#   vpn-assign comms direct              # Direct WAN for comms
#   vpn-assign dev blocked               # Kill switch — no traffic
#   vpn-assign --persistent browsing mullvad-browsing
#
#   vpn-assign on browsing               # Connect wg-browsing tunnel + assign
#   vpn-assign off browsing              # Route browsing direct (VPN bypass)
#   vpn-assign connect mullvad-browsing  # Bring up WireGuard tunnel
#   vpn-assign disconnect mullvad-browsing
#   vpn-assign list-mullvad              # List configured exit nodes
#   vpn-assign status                    # Show all assignments and tunnels

set -euo pipefail

# Re-exec with sudo if not root — ip route/rule require root
if [ "$(id -u)" != "0" ]; then
    exec sudo "$0" "$@"
fi

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

STATE_DIR="/var/lib/hydrix-vpn"
PERSISTENT_FILE="$STATE_DIR/persistent.conf"
NETWORK_MAP_FILE="/etc/hydrix-router/network-map"
INTERFACES_FILE="/etc/hydrix-router/interfaces"
VPN_DNS_FILE="/etc/hydrix-router/vpn-dns"

# Every table carries this unreachable default at the lowest priority. A table
# whose real default is missing (blocked, tunnel gone, never assigned) then
# fails closed instead of falling through to the main table's WAN route.
FALLBACK_METRIC=4294967295

# Routing table IDs and subnets — loaded from network-map at runtime
declare -A ROUTING_TABLES=()
declare -A NETWORK_SUBNETS=()

load_network_map() {
    if [ ! -f "$NETWORK_MAP_FILE" ]; then
        echo -e "${RED}Error: $NETWORK_MAP_FILE not found${NC}" >&2
        return 1
    fi
    while IFS=: read -r name table_id subnet; do
        [[ -z "$name" || "$name" =~ ^# ]] && continue
        ROUTING_TABLES["$name"]="$table_id"
        NETWORK_SUBNETS["$name"]="$subnet"
    done < "$NETWORK_MAP_FILE"
}

get_wan_interface() {
    ip route | awk '/^default/{print $5; exit}'
}

# Router-side TAP of a network, from the build-time map (IFACE_<NAME>=<tap>)
get_net_iface() {
    local var="IFACE_${1^^}"
    var="${var//-/_}"
    [ -f "$INTERFACES_FILE" ] || return 0
    (
        # shellcheck disable=SC1090
        source "$INTERFACES_FILE"
        echo "${!var:-}"
    )
}

seal_table() {
    ip route replace unreachable default metric "$FALLBACK_METRIC" table "$1"
}

# DNS for a network follows its traffic: tunnelled and blocked networks have
# their queries to the router DNATed to the in-tunnel resolver (unreachable
# while blocked), direct networks use the router's own resolver.
set_dns() {
    local network="$1" target="$2" iface dns
    iface=$(get_net_iface "$network")
    [ -n "$iface" ] || return 0
    nft delete element inet router vpn_dns "{ \"$iface\" }" 2>/dev/null || true
    if [ "$target" != "direct" ] && [ -f "$VPN_DNS_FILE" ]; then
        dns=$(cat "$VPN_DNS_FILE")
        nft add element inet router vpn_dns "{ \"$iface\" : $dns }" 2>/dev/null || true
    fi
}

# Re-apply DNS redirects from saved assignments (after a firewall reload)
sync_dns() {
    local network
    for network in "${!ROUTING_TABLES[@]}"; do
        [ -f "$STATE_DIR/${network}.assignment" ] || continue
        set_dns "$network" "$(cat "$STATE_DIR/${network}.assignment")"
    done
}

vpn_interface_exists() {
    ip link show "$1" &>/dev/null
}

get_vpn_interface() {
    local name="$1"
    ip link show "$name" &>/dev/null && echo "$name" && return
    ip link show "tun-${name}" &>/dev/null && echo "tun-${name}" && return
    echo ""
}

# Ensure one network's ip rule exists (vpn-policy-init installs all of them at
# boot; this covers a rule removed by hand). Table ID = subnet octet, matching
# /etc/iproute2/rt_tables. Only this network is touched: every extra process
# costs real time on the router's single vCPU, and the eww widget waits on it.
ensure_ip_rule() {
    local subnet="${NETWORK_SUBNETS[$1]}" table="${ROUTING_TABLES[$1]}"
    ip rule show | grep -q "from $subnet lookup $table" \
        || ip rule add from "$subnet" lookup "$table" priority "$table" 2>/dev/null || true
}

update_routing() {
    local network="$1"
    local target="$2"

    if [[ -z "${ROUTING_TABLES[$network]+_}" ]]; then
        echo -e "${RED}Error: Unknown network '$network'${NC}"
        echo -e "Known networks: ${!ROUTING_TABLES[*]}"
        return 1
    fi

    local table="${ROUTING_TABLES[$network]}"
    local net_subnet="${NETWORK_SUBNETS[$network]}"
    ensure_ip_rule "$network"

    ip route flush table "$table" 2>/dev/null || true
    seal_table "$table"

    # Re-add the directly-connected subnet route so router services (dnsmasq, DHCP)
    # sourcing from the bridge IP are not routed into the VPN/policy table.
    local net_iface
    net_iface=$(ip route show table main scope link | awk -v pfx="$net_subnet" \
        '$1==pfx{for(i=2;i<=NF;i++) if($i=="dev"){print $(i+1); exit}}')
    [ -n "$net_iface" ] && ip route add "$net_subnet" dev "$net_iface" table "$table" 2>/dev/null || true

    case "$target" in
        blocked)
            echo -e "${YELLOW}[$network]${NC} Blocked (kill switch)"
            ;;
        direct)
            # throw hands the lookup on to the main table, so direct networks
            # always follow the router's current WAN default (WiFi roaming,
            # WAN not up yet) instead of a copy of it.
            local wan
            wan=$(get_wan_interface)
            ip route add throw default table "$table"
            echo -e "${GREEN}[$network]${NC} Direct WAN (${wan:-not up yet})"
            ;;
        *)
            local vpn_if
            vpn_if=$(get_vpn_interface "$target")
            if [ -z "$vpn_if" ]; then
                echo -e "${RED}Error: '$target' is not connected${NC}"
                echo -e "${YELLOW}Run first: vpn-assign connect $target${NC}"
                return 1
            fi
            ip route add default dev "$vpn_if" table "$table"
            echo -e "${GREEN}[$network]${NC} → $vpn_if"
            ;;
    esac

    set_dns "$network" "$target"
    echo "$target" > "$STATE_DIR/${network}.assignment"
}

connect_vpn() {
    local vpn_name="$1"
    local conf="/etc/wireguard/${vpn_name}.conf"

    [ -f "$conf" ] || { echo -e "${RED}No WireGuard config for '$vpn_name'${NC}"; return 1; }

    if ip link show "$vpn_name" &>/dev/null; then
        echo -e "${YELLOW}$vpn_name already connected${NC}"
    else
        # Table=off means wg-quick only creates the interface + peer config.
        # WAN default route handles endpoint reachability — no host route needed.
        echo -e "${BLUE}Connecting $vpn_name...${NC}"
        wg-quick up "$vpn_name"
        echo -e "${GREEN}Connected: $vpn_name${NC}"
    fi
    restore_assignments "$vpn_name"
}

# Networks still assigned to a tunnel were sealed when it went away; route
# them through it again now that it is back.
restore_assignments() {
    local vpn_name="$1" network
    for network in "${!ROUTING_TABLES[@]}"; do
        [ -f "$STATE_DIR/${network}.assignment" ] || continue
        [ "$(cat "$STATE_DIR/${network}.assignment")" = "$vpn_name" ] || continue
        update_routing "$network" "$vpn_name"
    done
}

disconnect_vpn() {
    local vpn_name="$1"

    if ! ip link show "$vpn_name" &>/dev/null; then
        echo -e "${YELLOW}$vpn_name not connected${NC}"
        return 0
    fi

    # Clear routing for any bridge assigned to this tunnel
    for network in "${!ROUTING_TABLES[@]}"; do
        local assignment=""
        [ -f "$STATE_DIR/${network}.assignment" ] && assignment=$(cat "$STATE_DIR/${network}.assignment")
        if [ "$assignment" = "$vpn_name" ]; then
            local table="${ROUTING_TABLES[$network]}"
            ip route flush table "$table" 2>/dev/null || true
            seal_table "$table"
            echo -e "${YELLOW}Blocked $network until reassigned (was → $vpn_name)${NC}"
        fi
    done

    wg-quick down "$vpn_name"
    echo -e "${GREEN}Disconnected: $vpn_name${NC}"
}

show_status() {
    echo -e "${BLUE}=== VPN Routing Status ===${NC}"
    echo ""
    local wan
    wan=$(get_wan_interface)
    echo -e "WAN: ${GREEN}${wan:-none}${NC}"
    echo ""

    echo -e "${BLUE}Bridge Assignments:${NC}"
    for network in "${!ROUTING_TABLES[@]}"; do
        local assignment="blocked"
        [ -f "$STATE_DIR/${network}.assignment" ] && assignment=$(cat "$STATE_DIR/${network}.assignment")

        local color="$RED" icon="✗"
        case "$assignment" in
            blocked) ;;
            direct) color="$GREEN"; icon="→" ;;
            *)
                if vpn_interface_exists "$assignment"; then
                    color="$GREEN"; icon="🔒"
                else
                    color="$YELLOW"; icon="⚠"
                    assignment="$assignment (disconnected)"
                fi
                ;;
        esac
        printf "  %-12s ${color}%s %s${NC}\n" "$network:" "$icon" "$assignment"
    done
    echo ""

    echo -e "${BLUE}Active Tunnels:${NC}"
    local found=false
    while IFS= read -r iface; do
        found=true
        local ip_addr
        ip_addr=$(ip -4 addr show "$iface" 2>/dev/null | awk '/inet/{print $2}' | head -1)
        echo -e "  ${GREEN}$iface${NC}  $ip_addr"
    done < <(ip -o link show | awk -F': ' '{print $2}' | grep -E '^(mullvad-|wg-|tun)' || true)
    [ "$found" = false ] && echo -e "  ${YELLOW}none${NC}"
    echo ""

    echo -e "${BLUE}Routing Tables:${NC}"
    for network in "${!ROUTING_TABLES[@]}"; do
        local table="${ROUTING_TABLES[$network]}"
        local route
        route=$(ip route show table "$table" 2>/dev/null | grep '^\(throw \)\?default' | head -1 || true)
        if [ -n "$route" ]; then
            echo -e "  $network: ${GREEN}$route${NC}"
        else
            echo -e "  $network: ${RED}blocked (unreachable)${NC}"
        fi
    done
}

list_mullvad() {
    echo -e "${CYAN}=== Mullvad Exit Nodes ===${NC}"
    echo ""
    local found=false
    for conf in /etc/wireguard/wg-*.conf; do
        [ -f "$conf" ] || continue
        found=true
        local name endpoint active
        name=$(basename "$conf" .conf)
        endpoint=$(awk -F'= *' '/^Endpoint/{print $2}' "$conf" | head -1)
        if ip link show "$name" &>/dev/null; then
            active="${GREEN}[UP]${NC}"
        else
            active="${RED}[DOWN]${NC}"
        fi
        printf "  %-20s ${YELLOW}%-45s${NC} %b\n" "$name" "$endpoint" "$active"
    done
    [ "$found" = false ] && echo -e "${YELLOW}No Mullvad configs — fill in vpn/mullvad.nix and rebuild the router.${NC}"
    echo ""
    echo -e "${BLUE}Usage:${NC}"
    echo "  vpn-assign connect mullvad-browsing     # bring up tunnel"
    echo "  vpn-assign browse mullvad-browsing      # route browsing VM through it"
    echo "  vpn-assign pentest mullvad-pentest"
    echo "  vpn-assign --persistent browse mullvad-browsing"
}

vpn_on() {
    local network="$1"
    local tunnel="wg-${network}"
    if ip link show "$tunnel" &>/dev/null; then
        update_routing "$network" "$tunnel"
    else
        # connect_vpn re-routes networks already assigned to the tunnel
        connect_vpn "$tunnel"
        [ "$(cat "$STATE_DIR/${network}.assignment" 2>/dev/null)" = "$tunnel" ] \
            || update_routing "$network" "$tunnel"
    fi
}

vpn_off() {
    local network="$1"
    update_routing "$network" direct
}

save_persistent() {
    local network="$1" target="$2"

    if [ ! -f "$PERSISTENT_FILE" ]; then
        printf '# Hydrix VPN persistent assignments\n# network=target\n' > "$PERSISTENT_FILE"
        for n in "${!ROUTING_TABLES[@]}"; do
            echo "${n}=direct" >> "$PERSISTENT_FILE"
        done
    fi

    if grep -q "^${network}=" "$PERSISTENT_FILE"; then
        sed -i "s|^${network}=.*|${network}=${target}|" "$PERSISTENT_FILE"
    else
        echo "${network}=${target}" >> "$PERSISTENT_FILE"
    fi

    echo -e "${GREEN}Saved: $network → $target${NC}"
}

usage() {
    load_network_map 2>/dev/null || true
    local nets="${!ROUTING_TABLES[*]}"
    cat << EOF
Usage: vpn-assign <command> [args]

  on <network>                 Connect wg-<network> tunnel + assign
  off <network>                Route <network> direct, bypassing VPN
  <network> <target>          Assign bridge to VPN/direct/blocked
  --persistent <net> <tgt>    Assign and save across reboots
  connect <vpn>               Bring up WireGuard tunnel
  disconnect <vpn>            Tear down tunnel
  list-mullvad                List configured Mullvad exit nodes
  sync-dns                    Re-apply DNS redirects from saved assignments
  status                      Show assignments and active tunnels
  help                        This help

Known networks:  ${nets:-(load network-map to list)}
Targets:         mullvad-<name>  direct  blocked

Examples:
  vpn-assign off browsing                             # temporarily bypass VPN
  vpn-assign on browsing                               # reconnect through Mullvad
  vpn-assign browsing blocked                          # kill switch — no traffic
  vpn-assign --persistent browsing mullvad-browsing    # survive router restarts
  vpn-assign status                                    # show current assignments
EOF
}

main() {
    mkdir -p "$STATE_DIR"
    load_network_map

    case "${1:-}" in
        ""|status)    show_status ;;
        list-mullvad) list_mullvad ;;
        sync-dns)     sync_dns ;;
        on)
            [ -z "${2:-}" ] && { echo -e "${RED}Network name required${NC}"; exit 1; }
            [[ -n "${ROUTING_TABLES[${2}]+_}" ]] || { echo -e "${RED}Unknown network '$2'${NC}"; exit 1; }
            vpn_on "$2"
            ;;
        off)
            [ -z "${2:-}" ] && { echo -e "${RED}Network name required${NC}"; exit 1; }
            [[ -n "${ROUTING_TABLES[${2}]+_}" ]] || { echo -e "${RED}Unknown network '$2'${NC}"; exit 1; }
            vpn_off "$2"
            ;;
        connect)
            [ -z "${2:-}" ] && { echo -e "${RED}VPN name required${NC}"; exit 1; }
            connect_vpn "$2"
            ;;
        disconnect)
            [ -z "${2:-}" ] && { echo -e "${RED}VPN name required${NC}"; exit 1; }
            disconnect_vpn "$2"
            ;;
        --persistent|-p)
            [[ -z "${2:-}" || -z "${3:-}" ]] && { echo -e "${RED}Usage: vpn-assign --persistent <network> <target>${NC}"; exit 1; }
            [[ -n "${ROUTING_TABLES[${2}]+_}" ]] || { echo -e "${RED}Unknown network '$2'${NC}"; exit 1; }
            update_routing "$2" "$3"
            save_persistent "$2" "$3"
            ;;
        help|--help|-h) usage ;;
        *)
            # Treat first arg as network name
            local network="$1"
            [ -z "${2:-}" ] && { echo -e "${RED}Target required${NC}"; exit 1; }
            [[ -n "${ROUTING_TABLES[$network]+_}" ]] || { echo -e "${RED}Unknown network '$network'${NC}"; exit 1; }
            update_routing "$network" "$2"
            ;;
    esac
}

main "$@"
